### ISSUE TITLE
find doesn't respect the 'deadline' setting

### ISSUE THREAD

**Issue by bukzor** [HypothesisWorks/hypothesis#1213]
I found this while trying to limit the duration of my hypothesis.stateful.RuleBasedStateMachine test, since it uses `find` rather than `given`, which does respect the deadline setting.

**Comment by DRMacIver** [comment]
I think there are two orthogonal issues here (possibly three. I'm not *sure*, but I think you might have misunderstood what the deadline setting does - it limits each individual test case, not the length of the total run):

* find doesn't respect a *lot* of settings.
* stateful testing should use the same underlying mechanisms as `@given` rather than find, and should support its full feature set.

I'm not sure whether we really want to fix the first. In general `find` is a bit of an odd corner of the API, and some of the settings don't make sense for it. The latter we should definitely fix.
