### ISSUE TITLE
Does the integer strategy validate the ratio between min_value and max_value arguments?

### ISSUE THREAD

**Issue by fkromer** [HypothesisWorks/hypothesis#1262]
I am using the [`integers()` strategy](https://github.com/HypothesisWorks/hypothesis/blob/2b27ff82772d3cf6f772148117ebca948c3fd5b7/hypothesis-python/src/hypothesis/strategies.py#L244) in one of my strategies. I noticed that If do not explicitly check the `min_value` and `max_value` argument relationship with [this corresponding validation check](https://github.com/fkromer/rospbt/blob/validation/rospbt/ros1/generators/builtin_msg_field_types.py#L118) this [corresponding test](https://github.com/fkromer/rospbt/blob/validation/tests/builtin_msg_field_types_generators.py#L32) would fail. (Test name to be considered only, the docstring needs to be fixed.) It seems like [`check_valid_interval(lower_bound, upper_bound, lower_name, upper_name)`](https://github.com/HypothesisWorks/hypothesis/blob/2b27ff82772d3cf6f772148117ebca948c3fd5b7/hypothesis-python/src/hypothesis/internal/validation.py#L125) (which is [called in the `integer()` strategy](https://github.com/HypothesisWorks/hypothesis/blob/2b27ff82772d3cf6f772148117ebca948c3fd5b7/hypothesis-python/src/hypothesis/strategies.py#L257)) should do this argument validation already. Have I missed something?

**Comment by DRMacIver** [comment]
I think what you're missing is that argument validation is lazy in Hypothesis - it happens at the point that the test is run, not the point at which the function is called.

**Comment by fkromer** [comment]
Great. Thanks.

**Comment by DRMacIver** [comment]
> Great. Thanks.

BTW I'd encourage following this pattern (which we should document better, sorry) - it's much easier to localize failures that happen at test execution time rather than import time, and interacts better with other tooling (e.g. one use case of this is that it means you can write strategies that would be invalid if a skipif condition triggers)

**Comment by fkromer** [comment]
> BTW I'd encourage following this pattern (which we should document better, sorry)

Do you mean [`check_valid_interval()`](https://github.com/HypothesisWorks/hypothesis/blob/2b27ff82772d3cf6f772148117ebca948c3fd5b7/hypothesis-python/src/hypothesis/internal/validation.py#L125) kind of functions which are decorated with `@check_function`? Would I have to add the [`@cacheable` decorator like done for `integers()`](https://github.com/HypothesisWorks/hypothesis/blob/2b27ff82772d3cf6f772148117ebca948c3fd5b7/hypothesis-python/src/hypothesis/strategies.py#L242) to my strategies then? My current tests would fail and be obsolete then, right?

**Comment by Zac-HD** [comment]
Nope - `@check_function` is used to implement an internal coverage layer (ie we test that every call site has been both true and false in a test run).  `@cacheable` is used internally to cache the strategy definition for perf reasons that probably don't apply to you (because the underlying `integers()` will be cached).

You want `defines_strategy[_with_reusable_values]` - internally that turns it into a `LazyStrategy` object which is private API and does the magic.

IIRC `defines_strategy` is *also* private API, but doesn't change much.  The definitely-public-API way to do this would be to decorate everything with `@composite`.

**Comment by fkromer** [comment]
> Nope - @check_function is used to implement an internal coverage layer (ie we test that every call site has been both true and false in a test run).

Wow, that is pretty cool :smiley:

> @cacheable is used internally to cache the strategy definition for perf reasons that probably don't apply to you (because the underlying integers() will be cached).

Ok.

> You want defines_strategy[_with_reusable_values] - internally that turns it into a LazyStrategy object which is private API and does the magic.
> 
> IIRC defines_strategy is also private API, but doesn't change much. The definitely-public-API way to do this would be to decorate everything with @composite.

It there is no disadvantage eben using @coposite for all strategies I would add it later...
