### ISSUE TITLE
Citing hypothesis?

### ISSUE THREAD

**Issue by endrebak** [HypothesisWorks/hypothesis#1356]
In my supps, I write about testing my new library. I want to cite hypothesis. How should I do it?

**Comment by Zac-HD** [comment]
Hi @endrebak - thanks for asking!  We're planning to submit to [JOSS](https://joss.theoj.org/) "soonish", at which point there will be a proper reference with DOI and everything.  If you can't wait, I'd cite it as

> David MacIver, Zac Hatfield-Dodds, Alex Chan, and contributors.  2018.  *Hypothesis (Python package)*.  https://github.com/HypothesisWorks/hypothesis/

Of course, @DRMacIver may have a different view!

**Comment by DRMacIver** [comment]
For the moment we have [a CITATION file](https://github.com/HypothesisWorks/hypothesis/blob/master/CITATION). It could probably use a refresh, but it's not a bad start.

I'm still unsure what to do about the authors list - the CITATION just has me in it, but that's partly because that was much more accurate when it was written, and that definitely doesn't feel right these days. What do people do about citing the particle physics papers with hundreds of contributors?

**Comment by endrebak** [comment]
Thanks. I've seen README, INSTALL and so on but never CITATION. It would be wise to point to it in the docs. It did not show up when googling `cite hypothesis` even.
