### ISSUE TITLE
Upload wheels to pypi at the same time as the tar.gz

### ISSUE THREAD

**Issue by nthomas-mozilla** [HypothesisWorks/hypothesis#1360]
We use Hypothesis in [Balrog](https://github.com/mozilla/balrog), and [pyup](https://github.com/pyupio/pyup) to keep dependencies up to date. When Hypothesis releases a new version it seems the tar.gz is uploaded to pypi initially, then the wheels will be added some time later. Pyup isn't able to handle this case properly (pyupio/pyup#250) and creates a PR which will later cause problems (pip will prefer a wheel and only the tar.gz hash is present in the requirements.txt).

Would you be able to change your process to upload all the packages at the same time ?

**Comment by alexwlchan** [comment]
This is because we build the sdist in Travis, and the wheels in Appveyor, and the two jobs don’t really talk to each other.

@DRMacIver – I suspect you wrote this originally, do you remember why we don’t do it all in one or the other.

**Comment by DRMacIver** [comment]
> @DRMacIver – I suspect you wrote this originally, do you remember why we don’t do it all in one or the other?

There's no major reason we couldn't do it all at once right now, but once we start actually building proper binary wheels something like the current process will become essential because we need to be able to build them on the relevant platforms.

In theory I suppose we could have a separate release process that gathers them all together and only does the release once they're all built, but it would be a massive pain.

**Comment by Zac-HD** [comment]
None of the possible workarounds seem worth the pain they'd cause us, so I'm closing this issue as covered by the upstream pyupio/pyup#250.
