### ISSUE TITLE
3.64.0 introduced breaking change to HypothesisHandle

### ISSUE THREAD

**Issue by mattsb42-aws** [HypothesisWorks/hypothesis#1362]
```
============================================================================================ test session starts =============================================================================================
platform darwin -- Python 2.7.13, pytest-3.6.2, py-1.5.3, pluggy-0.6.0
rootdir: /Users/bullocm/git/base64io-python, inifile: setup.cfg
plugins: cov-2.5.1, hypothesis-3.64.0
collected 238 items / 1 errors                                                                                                                                                                               

=================================================================================================== ERRORS ===================================================================================================
__________________________________________________________________________ ERROR collecting test/functional/test_f_base64_stream.py __________________________________________________________________________
test/functional/test_f_base64_stream.py:43: in <module>
    @hypothesis.given(source=BINARY)
.tox/py27/lib/python2.7/site-packages/_pytest/mark/structures.py:213: in __call__
    store_legacy_markinfo(func, self.mark)
.tox/py27/lib/python2.7/site-packages/_pytest/mark/structures.py:250: in store_legacy_markinfo
    holder.add_mark(mark)
E   AttributeError: 'HypothesisHandle' object has no attribute 'add_mark'
---------------------------------------------------------------------------------------------- Captured stderr -----------------------------------------------------------------------------------------------

```

Ex:
https://travis-ci.org/awslabs/base64io-python/builds/397145142
https://travis-ci.org/awslabs/aws-dynamodb-encryption-python/builds/397189674

Testing these pinning against Hypothesis 3.63.0, everything works as expected but when pinned against 3.64.0 these errors appear.

**Comment by Zac-HD** [comment]
The bad news is that `HypothesisHandle` (the type of the `.hypothesis` attribute on tests) is actually new in 3.64, so the break is not so much that it's changed as that it *exists*.  See 3c9fa581d17f28cbb7932589620336dee5855a83 / #1343.

On further investigation, the problem is that the `pytest-hypothesis` plugin (which is built in) goes to add a pytest marker called `pytest.mark.hypothesis`, and then we have a namespace issue.  It looks like Pytest then *avoids* overriding the attribute - but doesn't emit a warning - and later code then blows up by assuming that the attribute *is* a pytest marker.

Proposed solution:

- Rename the `.hypothesis` attribute.  Technically breaks backwards compatibility, but IMO "this has never worked under Pytest, and it's a day old" is enough to justify that (cc @DRMacIver to confirm).  3.64.x should be out soon with this fix.
- Ask Pytest to emit a warning instead of handling attribute/mark clashes silently, so the next team can catch this before release (-Werror FTW) or at least have an easier time debugging.

**Comment by DRMacIver** [comment]
Hi @mattsb42-aws. So looking into this the problem is triggered by the fact that your code is applying a `@pytest.mark.hypothesis` to the tests. This is actually redundant, as we already apply this mark! Apparently we don't document this anywhere (whoops, sorry. We've got an open issue about improving the documentation of the pytest plugin #1238). 

Anyway, we think this error is a bug on the pytest end and are going to open an issue about that with them, but in the meantime my recommendation would be to remove all of the  `@pytest.mark.hypothesis` lines - the marker is already there, so they're not actually doing anything, and removing them will cause things to behave exactly as they did before but will avoid triggering the bug.
