### ISSUE TITLE
Question: Pytest fixture in hypothesis RuleBasedStateMachine test case

### ISSUE THREAD

**Issue by fkromer** [HypothesisWorks/hypothesis#1364]
I was not able to find an example on github about how to use a pytest `fixture` in a hypothesis state based test case (`RuleBasedStateMachine`). Could you give me a hint pls?

**Comment by DRMacIver** [comment]
Unfortunately the hint is that you can't - there's not really a way to do it, and there probably never will be.

Depending on your use case you might be able to make it work using [`run_state_machine_as_test`](https://hypothesis.readthedocs.io/en/latest/stateful.html#more-fine-grained-control) (this isn't very well documented right now, sorry) by passing the fixture in in your constructor, but note that the usual restriction that function level fixtures are run only once in this case will still apply.

**Comment by ldobrek** [comment]
Sorry to ping a closed issue, I have a follow up question. I use `run_state_machine_as_test` as this allows me to pass a complicated fixture which otherwise is quite a lot of hasle to build but I loose all of information about the statistics. I know this is a know and documented feature of `run_state_machine_as_test` but I wander how hard would it be to not loose this information?
On my end I can say it would make my life a lot easier.

**Comment by Zac-HD** [comment]
See #437 - the issue isn't that statistics are *lost* so much as that they are never visible to our pytest plugin and there is currently no other way to see them.

**Comment by DRMacIver** [comment]
This is maybe something we could revisit. Our pytest plugin *could* work differently than it does. It runs into complications with `find`, but given that we're deprecating that anyway we could just have it opt out of those.
