### ISSUE TITLE
Problems with conda-forge builds

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis#1448]
It seems the recent versions (3.66.16-19) have some problems with few of the tests on our conda-forge builds (https://github.com/conda-forge/hypothesis-feedstock/pulls) on all platforms. Please look into it.
I'm not knowledgeable enough about hypothesis internals to investigate but that blocks release of c-f packages.

**Comment by DRMacIver** [comment]
I think the problem is not actually the most recent versions of Hypothesis, but that there was a new version of pytest released yesterday and we update our versions on mondays! Release process race conditions, sigh.

I probably won't have any time to sort this out properly today, but if anyone else wants to look into it I *believe* all that needs to be done is to replace calls to this function https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/tests/pytest/test_fixtures.py#L29 with a direct use of `float('inf')` or some top level constant or something - the problem is that a bunch of tests in this file call it directly.
