### ISSUE TITLE
Problem on OSX py2.7

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis#1451]
We have got a problem on OSX py2.7 build for conda-forge packages:
https://travis-ci.org/conda-forge/hypothesis-feedstock/jobs/410755174
The rest of OSX builds are fine.

**Comment by DRMacIver** [comment]
Huh. How has that test ever passed on 2.7? Python 2 regex reprs aren't anything meaningful. I guess it must be hitting the regular expression cache so the two are actually the same instance.

(Same story as before: Probably won't get a chance to fix this today myself, but it's probably just a matter of changing the test to check pattern and flags rather than repr)

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/blob/fe60c8aae7fd8478ef08acfd9f8f852ec004c1e7/hypothesis-python/tests/cover/test_pretty.py#L701-L706

Proposed change to:

```python
r2 = eval(pretty.pretty(r), globals())
assert r.pattern == r2.pattern and r.flags == r2.flags
```

**Comment by jochym** [comment]
The problem persists on 3.66.22: https://travis-ci.org/conda-forge/hypothesis-feedstock/jobs/410777173
