### ISSUE TITLE
link "trivial django project" toystore

### ISSUE THREAD

**Issue by Kaligule** [HypothesisWorks/hypothesis#1458]
In the [documentation about generating django types](https://hypothesis.readthedocs.io/en/latest/django.html) we can read:

> For example, using the trivial django project I have for testing:

It would be helpfull to link to this trivial django project (called toystore) or to describe it more. This would make it possible to recreate the example, even for people who don't know much about django (like me).

A link to a supersmall repo would be sufficient in my opinion. We could also choose to link an example from the [official django tutorial](https://docs.djangoproject.com/en/2.1/intro/).

**Comment by Zac-HD** [comment]
[Here's the `toystore` project in our tests](https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python/tests/django/toystore) :smile: 

Looking at [the docs in question](https://hypothesis.readthedocs.io/en/latest/django.html?highlight=toystore), I think we should probably rewrite the examples to use e.g. [`django.contrib.auth.models.User`](https://docs.djangoproject.com/en/2.1/ref/contrib/auth/) rather than our custom version, and include a code block in the docs defining any custom model we refer to.

**Comment by Kaligule** [comment]
Thank you very much. This is easier to understand.
