### ISSUE TITLE
Better tools for managing example database

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#172]
The example database is very opaque right now and it is unclear what is in it. It would be extremely useful to have better tools for managing this, particularly in the light of #171.

**Comment by Zac-HD** [comment]
Given the level of dynamism involved, this doesn't really seem feasible, and so I'm closing it as "seemed like a good idea early on, hasn't turned out to be important/practical" - as evidenced by seven years without any progress.

(That dynamism: the keys into the database are dependent on runtime behaviour of both Hypothesis and downstream code (e.g. both Pytest and user-controlled); the values have no independent meaning beyond "bytes parsed by the strategies" which can change with user code and/or library changes in Hypothesis or downstream tools.  If we can't summarize the keys *or* the values, there's really not much to say about the database.)
