### ISSUE TITLE
Usage without tests?

### ISSUE THREAD

**Issue by bukowa** [HypothesisWorks/hypothesis#1724]
Hypothesis itself provides everything for generating random values. Is that possible to use it as a standalone library for values generation? If yes, how?

**Comment by Zac-HD** [comment]
(this really belongs on [stack overflow](https://stackoverflow.com/questions/tagged/python-hypothesis) under the `python-hypothesis` tag more than the issue tracker, but here goes)

Hypothesis generates *arbitrary* values, rather than strictly random ones, so if you expect any specific distribution of outputs you will probably be surprised.  It's also designed for testing, so there's no really good way to use it for standalone data generation and it's not particularly good for that (aside from the strategies API being a nice way to describe values I guess)

That said, all `@given` does is wrap the test function, so: you could define a test function that just appends the value to a global list, the run the "test" function and use the resulting contents of the list.  List length and side-effects may vary.
