### ISSUE TITLE
RFC: Disable `HealthCheck.hung_test`?

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1764]
Now that deadlines are on by default, should we disable the health check that errors when your tests have been running for five minutes?

The reasoning for adding it in was from [discussion when deprecating timeout](https://github.com/HypothesisWorks/hypothesis/pull/580). 

> I’m worried about the case where you’re drawing examples really slowly (or not at all), in which case it seems like the test would just run forever and never stop? Which seems sub-optimal.

Now that we have deadlines and they're enabled by default it means that the only ways to hit the hung test limit are:

1. By setting the deadline to something large or disabling it entirely.
2. By setting `max_examples` to be something high
3. By having a hard to shrink failing test with slow executions (e.g. when shrinking a deadline).

In the first two cases you've basically opted in to slow tests, in the third raising a health check seems unhelpful given that we have an error we could show the user. Perhaps we should introduce a timeout to shrinking with some warning that this is not a fully shrunk example and you should rerun it if you want one?

**Comment by Zac-HD** [comment]
In generation, I agree that enforcing the `deadline` and `max_examples` setting makes `HealthCheck.hung_test` redundant.  Since it's non-orthogonal and annoying, I'd vote to deprecate it and turn it into a no-op.

I think we should think about timeouts in the generation and shrinking phases separately here - though it doesn't change my view at all!

In shrinking, we currently stop when we reach the first of a fixpoint, or 500 shrinks.  
- We should report to the user if we have not reached a fixpoint through something more obvious than the "stopped because max_shrinks" statistic, and consider a heuristic that will keep shrinking after 500 (or a smaller / max_examples-dependent number) iff we're making decent progress.  e.g. X attempts without reducing buffer length or alphabet.
- We should also take advantage of the anytime properties to make shrinking report the current best value if interrupted by e.g. `^C` before propagating the `KeyboardExit` exception.
- I have a strong preference to keep the mental model simple: "Hypothesis will shrink to a fixpoint, or report exceptional circumstances".  No user control over that.
