### ISSUE TITLE
Support hypothesis.ini file based configuration

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#185]
It would be great if the Hypothesis settings system could locate and load a hypothesis.ini file (potentially also a tox.ini section).

This should support all of the settings you can define programmatically. It should also be possible to define multiple profiles.

Suggested format:

```ini
[default]
max_examples = 100
min_satisfying_examples = 1

[dev]
max_examples=10
min_satisfying_examples = 0
```

the above would change the settings for the default profile and define a new dev profile.

Additional features that would be useful:
1. Some programmatic way to ignore or relocate the ini file (this is actually tricky because you need a way of inserting it into before the ini file is loaded).
2. A command line flag for the py.test plugin to access the above.

**Comment by moreati** [comment]
I'm taking a stab at this

**Comment by Zac-HD** [comment]
We're closing this issue as `wontfix`, because supporting a config file is likely to be more trouble than it's worth and fail in ways that are seriously confusing to users.

For example: when should the config file be read - in relation to what setup stage of any test runner (`unittest`, `nose`, `pytest`, etc...)?  What about experimenting in the REPL? 
 There's no answer to this that doesn't sometimes let users down, so we're going to stick to config-via-code (`register_profile`, `load_profile` et al) and you can manage settings from anywhere that code can be run.
