### ISSUE TITLE
Use distinct DB keys for parametrized Hypothesis tests

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1996]
#1995 fixes an issue with database collision, but there's a deeper issue in that these tests should have been using distinct keys in the first place.

So I propose that we should firm up the design of  `_hypothesis_internal_add_digest` (currently only used for `run_state_machine_as_test`, so we need to decide on e.g. how multiple applications work), then use it for `@pytest.mark.parametrize` too on at least a best-effort basis.

**Comment by DRMacIver** [comment]
>  on at least a best-effort basis.

Best-effort might be quite bad. `pytest.mark.parametrize` can offer very general arguments that we might struggle to hash in a meaningful way.

I wonder if there's an easy way to get an incrementing sequence that corresponds to the parameter order? We can't just use the number of times the test has been run this process (which was my initial thought) for a wide variety of reasons (xdist, filtering of tests run, etc).

Another possibility is that rather than using distinct keys we could change the eviction behaviour to be in some way more relaxed when parametrizing.

**Comment by Zalathar** [comment]
Is there any reasonable way to get a suitable test name/identifier directly from pytest?

(If our DB key is based on the test name that xdist sees, then we should sidestep any xdist conflicts.)

**Comment by Zac-HD** [comment]
I was thinking of adding the pytest item id to the internal hash, which should deal with both issues. That's a unique string that identifies the test, so xdist and hashing both work.

**Comment by DRMacIver** [comment]
Ah, yes, that's a good solution.

**Comment by pckroon** [comment]
I would be happy to take a look at this in the spirit of Hacktoberfest. I still need to dig through the code a bit to get a feel for what change should go where. I'll get back here once I have an idea for an approach, I hope that will be somewhere later this week.
Beyond that I can't say anything on timescales, since I also have thesis to finish :sob:

**Comment by Zac-HD** [comment]
I just did a `git grep _hypothesis_internal_add_digest` to see the current uses - there's only one in the internals of stateful testing, and since there's no way for that to be pytest-parametrized you can just reuse the same logic 😄 

More specifically, go to the following branch:

https://github.com/HypothesisWorks/hypothesis/blob/f8dff6b13c2c6c85d8637497d44bd61f864e49d6/hypothesis-python/src/hypothesis/extra/pytestplugin.py#L181-L182

and add a check:

```python
if is_hypothesis_test(item.obj):
    item.add_marker("hypothesis")
    if we_can_tell_this_is_parametrized(obj):  # This is the tricky part!
        item.obj.hypothesis.inner_test._hypothesis_internal_add_digest = \
            item.nodeid.encode("utf-8")
```

And then write a test under `hypothesis-python/tests/pytest/` that checks we end up with more than one entry from a `@parametrized` test with an `InMemoryDatabase`.

**Comment by pckroon** [comment]
Sounds good. I'll try to find some time soon :)
