### ISSUE TITLE
Parallel Generation of Examples

### ISSUE THREAD

**Issue by thedrow** [HypothesisWorks/hypothesis#2061]
Sometimes you want to generate a lot of examples to ensure you are correct in your assumption.
These may take a while to generate.

I'd like to have an option to parallelize the generation of examples using processes in Python.
Is that currently possible?

**Comment by Zac-HD** [comment]
No, it's not currently possible - #171 is definitely something we want to do, but there's no fixed timetable.  You could do a partial version just by running several Python processes; though I'd suggest setting a different database location per process.

We don't (yet) support this out of the box because many things-being-tested can't be interleaved, and it's rare for users to be running only one Hypothesis test at a time - if you have several, pytest-xdist and similar solutions just work.
