### ISSUE TITLE
strategy.functions in given and getting to the returned value

### ISSUE THREAD

**Issue by consal** [HypothesisWorks/hypothesis#2081]
Hi,

I have a question regarding the `functions` strategy. I use it as part of the `builds` strategy to build an object. One of the methods of this object is mocked with what comes from the `functions` strategy with:
```
st.functions(returns=st.integers(1, 1000)),
```
So for example `instance.my_function()` calls a function generated with the snippet above.

Then in my test case, I want to test that something happened depending if the function returned a value larger than 100. But I don't have access to the value that the function returns in my object. If I call again `instance.my_function()` I'll get another value:( I hope you get my point. Is there any way around that?
Cheers!

**Comment by Zac-HD** [comment]
Hey @consal!  FYI this kind of question is probably better off on StackOverflow when the questions with `python-hypothesis` tag are archived for posterity :slightly_smiling_face: 

I think the idiomatic solution to this problem isn't specific to Hypothesis - it sounds like you need a decorator that records values (or just the most recent value) returned by a function.  

Alternatively, if you're calling it without any arguments you could just cache the output so that subsequent calls *do* return the first value!  [`functools.lru_cache`](https://docs.python.org/3/library/functools.html#functools.lru_cache) would be a good choice for this, and you can even peek into the cache to see the arguments and return values it's seen: 

```python
st.functions(returns=st.integers(1, 1000)).map(functools.lru_cache()),
```

I hope that helps!
