### ISSUE TITLE
.hypothesis directory always created (pytest plugin)

### ISSUE THREAD

**Issue by fredludlow** [HypothesisWorks/hypothesis#2106]
Hi,

I've just started using hypothesis. Many thanks for a great package. One small issue (which I couldn't find reported elsewhere but maybe my lack of google-fu...) is that, now I have it installed, any time I run pytest (whether or not the particular package I'm testing uses hypothesis) a .hypothesis directory is created. e.g.

Minimal test-case given an environment with pytest and hypothesis installed:
```shell
mkdir t
cd t
echo "def test_me(): assert True, 'what?'\n" > test_me.py
pytest       # 1 test passes
ls -la         # shows a .hypothesis directory (amongst others)
```

It's not harmful, but it was a bit surprising.

**Comment by Zac-HD** [comment]
It would be good if we deferred  creation of that directory to the first write!

**Comment by pckroon** [comment]
I'd be happy to have a go at this in the spirit of hacktoberfest (so somewhere next week).
As I see it this would require only a few small changes:
1) No longer make the directory as part of configuration (in `configuration.py`). Instead, DirectoryBasedExampleDatabase gets to create it on `__init__` or `save`.
2) Change the permission checks in `_db_for_path`. That would require the assumption that if we can write in the base folder of the __hypothesis_home_dir, we can make our database dir there. Only applicable if the database dir does not exist yet, otherwise we can check the permission of that folder.
3) Tests for the new behaviour.

Would this sum it up, or am I missing something crucial that would result in an awful pile of work and refactoring?

**Comment by Zac-HD** [comment]
That sounds about right to me - it should indeed be a nicely scoped PR for hacktoberfest :smile:

**Comment by fredludlow** [comment]
Great - thanks for looking into it! (And hope you get the t-shirt ;) ).

**Comment by FilipeMarch** [comment]
Every time I run `pytest` on any project I see this `.hypothesis` folder created on the project's folder, then I need to add it to .gitignore, it is annoying. Is there a way for asking to pytest to not create this `.hypothesis` folder?

**Comment by rsokl** [comment]
> Is there a way for asking to pytest to not create this .hypothesis folder?

Are you using hypothesis in your test suite? If so, it is hypothesis, not pytest, [that is creating this example database](https://hypothesis.readthedocs.io/en/latest/database.html).
