### ISSUE TITLE
How can I filter a small set of integers from the integers() strategy?

### ISSUE THREAD

**Issue by FunkyLoveCow** [HypothesisWorks/hypothesis#2146]
I'm attempting to validate yearly subscription terms. We price our product based on the number of years you've pre-paid.

My decorator was going to look something like this:

    from hypothesis import given
    import hypothesis.strategies as st
    
    @given(term=st.integers().filter(lambda x: x in [1, 2, 3, 4]))

However, this throws a `FailedHealthCheck` telling me I've filtered out a lot of data.

How can I properly filter out these specific integers from being passed to the test case?

**Comment by DRMacIver** [comment]
In general you shouldn't use filter for hard to satisfy conditions, it's much better to try to construct a strategy that gives you the right data without filtering. In this case the relevant strategy is the standard [sampled_from](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.sampled_from) from Hypothesis's library of strategies.

Also, for pure usage questions like this it's better to use [the stackoverflow tag](https://stackoverflow.com/questions/tagged/python-hypothesis) rather than the issue tracker, which is intended for bugs and feature requests.
