### ISSUE TITLE
`nocover/test_respects_max_examples_in_database_usage` is flaky

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2251]
```python-traceback
_________________ test_respects_max_examples_in_database_usage _________________
[gw0] linux2 -- Python 2.7.13 /home/vsts/work/1/s/hypothesis-python/.tox/pypy-full/bin/python
Traceback (most recent call last):
  File "/home/vsts/work/1/s/hypothesis-python/tests/nocover/test_database_usage.py", line 124, in test_respects_max_examples_in_database_usage
    assert len(all_values(database)) > 10
AssertionError: assert 10 > 10
 +  where 10 = len(set([compatbytes(...), ...]))
 +    where set([compatbytes(...), ...]) = all_values(InMemoryExampleDatabase({'a database key': set([compatbytes(...)])}))
```

[Via this CI failure](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=3107&view=logs&jobId=d1cafe0c-32b1-5c9c-e54f-8f4972aa4ad6&taskId=32d1317c-102d-5d27-f947-f1b7daa52934&lineStart=485&lineEnd=493&colStart=1&colEnd=1).  I don't *think* this is a Py2-only or pypy-only issue, or both, but it might be.  [This one](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=3097&view=logs&jobId=d1cafe0c-32b1-5c9c-e54f-8f4972aa4ad6&taskId=32d1317c-102d-5d27-f947-f1b7daa52934&lineStart=485&lineEnd=493&colStart=1&colEnd=1) also happened on pypy2, so...

**Comment by Zalathar** [comment]
I looked into this briefly when I ran into it the other day.

It seems to be failing during a setup step, not during the actual interesting part of the test. So I suspect the test isn't reliably setting up its initial assumptions.

We can probably just put a `deterministic_PRNG` around the first call to `stuff()`, so that the setup will succeed consistently.
