### ISSUE TITLE
Sample according to state in RuleBasedStateMachine

### ISSUE THREAD

**Issue by MaxG87** [HypothesisWorks/hypothesis#2302]
In a personal project I have one long lived object whichs API I want to test. I hold this object as a member of my RuleBasedStateMachine and mirror most of the APIs as rules. However, in certain circumstances, I need to generate/sample input data depending on the state of my long lived object.

Please consider the following minimum working example. It fails because `self` is not known in the place where I need it.
```python
from hypothesis.stateful import rule, RuleBasedStateMachine
import hypothesis.strategies as st


class SimpleTest(RuleBasedStateMachine):
    def __init__(self):
        self.my_list = []

    @rule(name=st.text())
    def append(self, name):
        self.my_list.append(name)

    @rule(index=st.integers(min_value=0, max_value=len(self.my_list)))
    def remove_elem(self, index):
        self.my_list = self.my_list[:index] + self.my_list[index+1:]
```

Here the long lived object is a list. I need to test to remove elements based on their indices in a list. This might seem odd but is caused by some user interface.

Is it possible to adjust the sampling based on 'self'? If not, is there a idiomatic workaround?

**Comment by Zac-HD** [comment]
There are a couple of options here:

- Using `st.data()` would allow you to construct the `integers()` strategy *inside* your `remove_elem` rule.  This is how I'd do it - the only downside is that failing examples show the index as a special draw rather than an argument to the method.
- You *could* instead pick a reasonable upper bound for the length of the list, then `assume(index < len(self.my_list))`.  Looks very elegant, but filtering can lead to lots of retries.

Hope that helps!

**Comment by MaxG87** [comment]
Thank you very much. I was not aware of st.data.
