### ISSUE TITLE
Test failure with Python 3.9

### ISSUE THREAD

**Issue by Dormouse759** [HypothesisWorks/hypothesis#2348]
Hypothesis test test_typeddict_with_optional_then_required_again in hypothesis-hypothesis-python-5.5.1/hypothesis-python/tests/cover/test_lookup_py38.py fails with Python 3.9.

I have tried to debug this issue, but I am quite lost in the project's logic.

I have at least prepared an environment in which it is possible to reproduce:
https://github.com/Dormouse759/fedora-rawhide-cont

Once built, just run ./reproduce.sh inside the container.

Downstream issue: https://src.fedoraproject.org/rpms/python-hypothesis/pull-request/6#comment-36386

Should you have any directions where to look, I will gladly give this bug a second try.

**Comment by Zac-HD** [comment]
Related pull requests: #2208 ([Hypothesis 4.45](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-45-0)), python/cpython#17214 (for 3.9), python/typing#687 (unreleased)

Blast.  I'll just redact the rest of the investigation and the swearing - turns out that while the logic in Hypothesis is correct, I got the logic for propagation of non-optional keys where others *are* optional wrong in CPython.  I'll need to fix it (and add more tests) upstream there and in `typing_extensions` 😬 

My sincere thanks for reporting this before it made it into a release!

**Comment by hroncok** [comment]
@Zac-HD Could you pleas point to the fixer?

**Comment by Zac-HD** [comment]
Not fixed yet, I'd just closed it because I think it's an upstream issue.  Reopening until I have a concrete reference (or fix) to point to instead.

**Comment by hroncok** [comment]
Thanks.

**Comment by hroncok** [comment]
Seem to be OK with hypothesis 5.8.0 and Python 3.9.0a5.

**Comment by Zac-HD** [comment]
Seems to be working, so... :man_shrugging:
