### ISSUE TITLE
note() equivalent for a callable

### ISSUE THREAD

**Issue by james-w** [HypothesisWorks/hypothesis#235]
Hi,

As you know the repeated running of the test function makes things like
reporting details of the failed run tricky, hence providing note().

However, not everything that you want to report is a string to be printed.

In particular I use testtools, which has 'details' that you attach to a test
run. I'd like to be able to use similar to note().

I think providing something like note() that takes a callable, and only
fires the callable if is_final would be generally useful.

Thanks,

James

**Comment by DRMacIver** [comment]
I wondered about this when introducing note. One of the problems with it is that it changes the exact nature of what runs a lot more than note() currently does - in particular it introduces new opportunities for failure (what if you have a bug in your printing?), or for success (what if the callable has side effects?). 

I'm not against this and think it's a good idea, but there are some tricky edge cases that need some careful managing, which is why it didn't make it into the initial implementation.

**Comment by Zac-HD** [comment]
Experience since this issue was opened suggests that restricting notes to strings (or str-able objects) is actually pretty useful.  If you have a callable, the result will still be reported as a string - and it should be called for each example for reproducible results and shrinking.

Using the existing API, `note(...)` will only report data from the final case, while `event(...)` will report statistics of the data from all cases.

**Comment by tomprince** [comment]
> Experience since this issue was opened suggests that restricting notes to strings (or str-able objects) is actually pretty useful.

I don't think that the intention of this ticket was to have notes with data that is generated at print time, but rather to enable calling [`testtools.TestCase.addDetail`](https://testtools.readthedocs.io/en/latest/for-test-authors.html#details). The idea was to be able to call that only on the final case, so that only the details of the final failing run are added.

**Comment by Zac-HD** [comment]
> [Calling something only in the last example] introduces new opportunities for failure (what if you have a bug in your printing?), or for success (what if the callable has side effects?).

I think another solution, perhaps clearing saved details before each new example, would be more robust in general.
