### ISSUE TITLE
Feature request: Access to logging

### ISSUE THREAD

**Issue by ShadowLNC** [HypothesisWorks/hypothesis#2352]
I'm using Hypothesis in a custom test framework, which captures logging, but ignores stdout/stderr.

While I can (and likely will) redirect the streams to be captured in the interim, would it be possible to please have Hypothesis log its messages through the Python `logging` module and have a handler then send that to the streams (ideally with a setting to disable stream output), such that I could add my own handlers within my test framework?

**Comment by Zac-HD** [comment]
@ShadowLNC - I think that's covered by this function:

https://github.com/HypothesisWorks/hypothesis/blob/f781f78cab528786fbc1a3aa27da0769b6af4109/hypothesis-python/src/hypothesis/reporting.py#L27-L31

Could you put togther an example PR that would work for you?

**Comment by ShadowLNC** [comment]
Thanks for pointing out the reporting module - I was able to wrap the custom test runner with `with with_reporter(<logging function>):` (I could have also used `reporter.value = ...`). I note that this doesn't seem to be documented when I search for "reporting" or "reporter" - is this an internal API?

I'm happy for this ticket to become closed or repurposed for adding docs if it's meant to be documented but isn't already.

**Comment by Zac-HD** [comment]
We do consider this to be private / internal and therefore subject to change, but in practice it's been pretty stable.  Glad to hear it's working for you!

I think we'll keep it undocumented though, because as a volunteer I simply can't commit to supporting everything and 'test framework can't capture stdout' is not a high priority, especially when there's a decent workaround.
