### ISSUE TITLE
Parameter name clash in extra.django.from_model

### ISSUE THREAD

**Issue by DanLipsitt** [HypothesisWorks/hypothesis#2369]
`from_model`'s first argument is `model`:

https://github.com/HypothesisWorks/hypothesis/blob/d159096999e9e65c77039a25f539ea0717a9f1de/hypothesis-python/src/hypothesis/extra/django/_impl.py#L57-L59

This leads to an error when trying to write a strategy for a class that has a field named `model`. For example:

```python
from django.db.models import Model, CharField
class Car(Model):
    model = CharField(help_text="The model of the car.")

car_strategy = from_model(Car, model='Mustang')
```

This will result in the following error:

```
TypeError: from_model() got multiple values for argument 'model'
```

Perhaps the first argument to `from_model` could be named `_model` or `_hypothesis_model` or something like that?

**Comment by Zac-HD** [comment]
Ah, we had the same problem with `builds()` (#1106), which was fixed by manual validation of `*args` - it's inelegant, but fixes the problem.

In Python 3.8 (or later), we can instead use a named positional-only argument... but that's years away.  Until then we can patch the `__signature__` to fix our docs, like #2345, and get better introspection on new Pythons for free.
