### ISSUE TITLE
Breadth first mode

### ISSUE THREAD

**Issue by MaxG87** [HypothesisWorks/hypothesis#2374]
I am using the fantastic Hypothesis framework (thank you very much) extensively. Locally I have `max_examples=10` and in CI I have `max_examples=200` to control the runtime of the test suite.

From time to time I would like to run extensive tests that would run very long, say, over night. Currently I estimate an appropriate value of `max_examples` based  the current run time and on the time I am willing to spend. However, that does not work out all the time. Sometimes I misestimate, sometimes I do not know how much time I could spend, e.g. over lunch break.

I would like to have a breadth first mode. In this mode, hypothesis would have no upper limit for `max_examples` but instead run all tests in the same proportion, forever. Thus, if I have 10 tests and an hour of runtime, Hypothesis would have executed each test 1,000 times instead of 5 tests 20,000 times and the others not at all.

This is very similar to #171, but there are subtle differences. In particular, in this scenario it is okay to stop at the first error.

**Comment by Zac-HD** [comment]
I'm definitely keen to support a run-indefinitely mode with adaptive test scheduling. That means instead of fixed proportions, gradually spending larger fractions of the time on more complex tests. 

#2371 will make it very easy to write a prototype - generate a random bytestring, feed it to each of the fuzz_one_input targets, and repeat indefinitely.

**Comment by MaxG87** [comment]
It seems as if this is about to be merged?! Awesome!
