### ISSUE TITLE
Using example decorator on its own (without given)

### ISSUE THREAD

**Issue by SaschaSchlemmer** [HypothesisWorks/hypothesis#2405]
I noticed that `@example` cannot be used without `@given` which would imho. be useful for cases where a suitable test strategy is not obvious and one wants to start with some handcrafted examples. 

```python
@example('math.sin(1)', math.sin(1))
# and so on
@example('2+2', 4)
def test_eval(expr, result):
    assert eval(expr) == result
```
which can then be later improved when one has figured out a suitable strategy

```python
@example('math.sin(1)', math.sin(1))
# and so on
@example('2+2', 4)
@given(my_fancy_strategy)
def test_eval(expr, result):
    assert eval(expr) == result
```

A workaround I found is

```python
@example('math.sin(1)', math.sin(1))
# and so on
@given(just('2+2',) just(4))
def test_eval(expr, result):
    assert eval(expr) == result
```

...however this doesn't look as nice and I guess I would also need to use `@settings` to not try the `just` strategy the default amount of times?

**Comment by Zac-HD** [comment]
```python
@example('math.sin(1)', math.sin(1))
# and so on
@given(nothing(), nothing())       # nothing() is generic placeholder strategy
@settings(phases=[Phase.example])  # Skip other phases (because you can't generate nothing)
def test_eval(expr, result):
    assert eval(expr) == result
```

But we're not likely to support this in general, because either (a) you don't intend to use `@given(...)` later and should use `@pytest.mark.parametrize(...)` instead, or (b) you *do* and supporting `@example`-without-`@given` risks forgetting to apply the latter.

> I guess I would also need to use @settings to not try the just strategy the default amount of times?

Hypothesis is smart enough to tell that there's only one possible test case from `@given(just(...))`, and stop after running it just once.  So your `just()` trick is probably nicer than my `nothing()`-plus-settings :smile:
