### ISSUE TITLE
Strategy type annotations - explicit Optional

### ISSUE THREAD

**Issue by davidmascharka** [HypothesisWorks/hypothesis#2424]
A lot of the strategies in [core](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies/_internal/core.py) take parameters that can be `None`-valued but aren't typed as `Optional`. For example,

``` python
def integers(min_value: int = None, max_value: int = None) -> SearchStrategy[int]:
```

which can cause issues if mypy is run with `--no-implicit-optional`. The only strategy that has (partially) typed `Optional` in core is `complex_numbers`:

``` python
def complex_numbers(
    *,
    min_magnitude: Optional[Real] = 0,
    max_magnitude: Optional[Real] = None,
    allow_infinity: bool = None,
    allow_nan: bool = None
) -> SearchStrategy[complex]:
```

Would you like to have a PR updating the rest of the strategies with explicit `Optional` types or do you prefer relying on implicit optional (in which case perhaps remove it from `complex_numbers` for consistency)?

**Comment by Zac-HD** [comment]
Hey David - thanks for pointing this out!  My personal preference is for strict, implicit optional: it's exactly equivalent for mypy and also `typing.get_type_hints` at runtime, and avoids some redundancy.

If it's causing issues downstream though (@Stranger6667 might chime in?), I'd accept a `--no-implicit-optional` PR and live with the aesthetics.  Otherwise, a PR `st.complex_numbers()` would also be welcome!

**Comment by Stranger6667** [comment]
@Zac-HD 
Hi! There are no issues caused by this in Schemathesis (at least from what I can see) :) I just looked at the issue and added :+1: because of my personal preferences :) I actually thought, that with `--no-implicit-optional` mypy won't allow `None` arguments if they aren't declared as `Optional` which could prevent some bugs, but I am not sure if it actually behaves like this

**Comment by Zac-HD** [comment]
> I actually thought, that with `--no-implicit-optional` mypy won't allow `None` arguments if they aren't declared as `Optional` which could prevent some bugs

You're correct, but IMO we have good enough code review that on balance I prefer the more concise form.  Thanks for the comment!

@davidmascharka I would therefore prefer to change `st.complex_numbers()` :slightly_smiling_face:
