### ISSUE TITLE
Type annotations used for `functions` strategy

### ISSUE THREAD

**Issue by lengau** [HypothesisWorks/hypothesis#2425]
When you accept a function as a parameter to another function, if you're using `mypy` and `typing` you may well have that method described already using `Callable` etc. In this case, it's redundant to create a lambda function for the `like` attribute of `hypothesis.strategies.functions`. It would be nice to be able to reuse these objects in hypothesis.

**Comment by Zac-HD** [comment]
It's not quite clear to me what you're asking for.  If you mean "`st.functions(like=Callable[[int, int], int])` should work", you're better off using `st.from_type()`.

If you mean "`st.functions()` ought to infer a strategy for `returns` from the return-type annotation on the `like` function", that sounds pretty good to me!  I'd be happy to help out if you'd like to open a PR: `hypothesis.internal.compat.get_type_hints(func).get("return", type(None))` and `st.from_type()` should get you started :smile:

**Comment by akash-suresh** [comment]
Hey @Zac-HD ! I would like to pick this up. But I would need some guidance on how to get this done. 😄

**Comment by Zac-HD** [comment]
Sure!  I'll keep the tips a little vague, because figuring out how to do it is part of the fun.  Getting stuck isn't fun for long though, so if you're getting frustrated just push what you have up and ask me for more detailed advice.

1. Find the definition of the `functions()` strategy.
2. We're going to change the default value of the `returns` argument to `None` (instead of `st.none()`).
3. If a strategy is passed, same logic as now.
4. If `returns is None`, we want to get the return-type annotation of the `like` argument using our `get_type_hints` function.
5. Use `st.from_type()` to get the strategy, defaulting to `st.none()` if there is no return type hint (again, the current behaviour)
6. Write some tests in `tests/cover/test_functions.py` to check that it's working.
7. Write release notes in a new file `hypothesis-python/RELEASE.rst` for a minor release.  Check some of the other PRs for examples of this.
8. Add your name to the list of contributors in `CONTRIBUTING.rst`

and that's it!
