### ISSUE TITLE
Please make it possible to disable health checks via pytest command-line args

### ISSUE THREAD

**Issue by mgorny** [HypothesisWorks/hypothesis#2533]
Health checks are certainly valuable to package managers but they sometimes fire when testing packages on end-user systems. For end users, the important feature of tests is to determine whether the package works, and it is entirely undesirable for tests to fail unpredictably because e.g. they are too slow. Could you, please, provide an option to easily disable all health checks via pytest command-line arguments, so users could run tests reliably without having them fail unpredictable due to bugs that have to be fixed by package maintainers?

**Comment by mulkieran** [comment]
This _might_ be done by having Hypothesis itself establish a separate profile, its own CI profile, that can be set by the hypothesis-profile pytest flag as explained here: https://hypothesis.readthedocs.io/en/latest/settings.html?highlight=profiles#settings-profiles.

This _might_ be somewhat helpful to me, also, as I package some libraries for upstream and also for Fedora, and the Hypothesis-based testing occasionally fails during Fedora packaging. However, often I want the version of the same library to run on different systems that support different versions of Hypothesis and I generally make use of more modern versions of Hypothesis when I make testing improvements, causing failures on older systems. Also, while Hypothesis is very effective at finding bugs, it _is_ unpredictable due to the randomization that is built in to it. I feel that Hypothesis-based tests are misapplied when used to check downstream packaging. My project actually has an issue out about this: https://github.com/stratis-storage/project/issues/179, which we have had no chance to pursue.

(I didn't put together the original downstream packages, or it might have occurred to me to avoid using Hypothesis at that time.)

**Comment by Zac-HD** [comment]
Hypothesis provides the settings profiles functionality, but choosing which to use - like build stability in general - is a decision for our downstream packages rather than us.  I'd second @mulkieran's observation that CI tests are not always good packaging/regression tests; [*Two Kinds of Testing*](https://blog.nelhage.com/post/two-kinds-of-testing/) describes the difference pretty well.

You might be able to do something useful with `sitecustomize.py` and profiles though, or just `pytest -m "not hypothesis"`, but that's about as much help as I can offer :confused:

**Comment by mgorny** [comment]
Just wanted to say, that 4 years later, this is still a proper nightmare.

1. I don't really have the time for this, yet I keep reporting failing health checks all over the place. In many cases, these bug reports hang forever, because people just don't care.
2. Disabling all testing using Hypothesis is not an option, because often these are the only tests for a given part of the library. Disabling them means lowering test coverage.
3. In the end, downstream testers want to know whether the package works. Health check failures are basically random false positives.
