### ISSUE TITLE
target() cannot be called outside a hypothesis test

### ISSUE THREAD

**Issue by aarchiba** [HypothesisWorks/hypothesis#2581]
I have a test `assert_allclose_phase` which checks whether two arrays are almost equal modulo one. When running under `hypothesis`, this seems like a sensible place to put `target`, albeit with a(n optional?) `name` argument in case I want to call it twice in the same test. Unfortunately if I do so then I can't use the same function in non-`hypothesis` tests:

```
E           hypothesis.errors.InvalidArgument: Calling target() outside of a test is invalid.
```

My current workaround is to call `target` only if `name` is provided, but this clutters simple tests that wouldn't need a `name`.

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/blob/caccabbd107757ee6e9de1de7e3cff5474d9ccc5/hypothesis-python/src/hypothesis/control.py#L173-L175

I'd be happy to add an optional keyword-only argument like `allow_outside_given_test=False`, and if `True` add an early return inside this check.  The idea would be to continue catching accidental use outside `@given`-tests, which would be a noop, but also support this kind of helper function which may be used outside them too.

**Comment by PurpleDevAu** [comment]
I'll give this a shot, if no one has yet

**Comment by Zac-HD** [comment]
Thanks to @PiDelport in https://github.com/HypothesisWorks/hypothesis/pull/2675#pullrequestreview-547298906, I've come around to the idea that instead of a special-case argument, we should provide a general predicate.  For example:

```python
if hypothesis.currently_in_test_context():
    # We're in an @given or stateful test, and can safely use e.g.
    target(x)
    event("hello")
    assume(foo)
    if bar: reject()
```

This should still be documented as "only use this in test helper functions", but I think it would be of sufficient if niche interest to justify its existence - and more orthogonal/composable than supporting similar capabilities on a function-by-function basis.
