### ISSUE TITLE
[enhancement] Unpack one strategy into multiple parameters

### ISSUE THREAD

**Issue by charles-staats** [HypothesisWorks/hypothesis#2642]
It's pretty common for me to want to have multiple parameters with some relation between them; for instance, two lists that are the same length. Currently, according to stackoverflow answers such as https://stackoverflow.com/a/54428719/2318074, there is no way to do this other than combining the parameters into a single tuple and then unpacking that tuple within the body of the test itself. I am requesting an alternative version of the `given` annotator that unpacks a tuple into *args or a dict into **kwargs of the nested function.

**Comment by Zalathar** [comment]
Hmm, would it be possible to achieve the same result by defining a standalone decorator that converts your multi-arg function into a one-tuple-arg function, and then using both decorators in the appropriate order?

**Comment by Zac-HD** [comment]
I'm closing this issue because it's possible to implement outside Hypothesis, and in my view the cost of expanding our API (more to learn, test, document, etc) outweighs the benefit.

**Comment by sschuldenzucker** [comment]
I hit some issues here when a function also uses named fixtures (defined in `conftest.py`): When wrapping function call information using `@functools.wrap` in the decorator, hypothesis doesn't see that the function now takes at least one parameter less and looks for a fixture for the first parameter. Without using `@functools.wrap`, the decorator loses the information about the argument names and we cannot use named fixtures. Both of these are not practical.

So what the decorator would need to do is a variant of `@functools.wrap` that adjusts the call information based on the number of arguments that is to be unpacked. But this seems rather involved, so that perhaps hypothesis should actually provide this decorator? (perhaps in a helper library)

**Comment by honno** [comment]
As an aside, using `st.shared()` can achieve a decent way in creating a "strategy factory" which returns multiple strategies with shared properties, that can be literally unpacked (i.e. `*args`) in a `@given()` decorator.

I think it's still a bit magical and finicky, but this has been useful when I'm requiring an "unpacked strategy" dozens/hundreds of time. One example has been writing tests which take two mutually-broadcastable NumPy arrays as inputs, e.g.

```python
from hypothesis import numpy as nps

def two_mutually_broadcastable_arrays():
    shared_dtypes = st.shared(nps.scalar_dtypes())
    shared_mutual_shapes = st.shared(
        nps.mutually_broadcastable_shapes(2).map(lambda BS: BS.input_shapes)
    )
    arrays1 = nps.arrays(
        dtype=shared_dtypes,
        shape=shared_mutual_shapes.map(lambda pair: pair[0]),
    )
    arrays2 = nps.arrays(
        dtype=shared_dtypes,
        shape=shared_mutual_shapes.map(lambda pair: pair[1]),
    )
    return arrays1, arrays2


@given(*two_mutually_broadcastable_arrays())
def test_my_binary_func(x1, x2):
    ...
```
