### ISSUE TITLE
Upgrade `st.register_type_strategy` to work as a decorator

### ISSUE THREAD

**Issue by rvodden** [HypothesisWorks/hypothesis#2650]
Hey all, 

I have a couple of ideas for low priority enhancements which I'd like to run past you. I've implemented both as proof of concepts and more than happy to submit an upstream PR, but wanted to sound you out first.

Firstly, and I appreciate what @DRMacIver has said about [a smooth transition from types to strategies](https://github.com/HypothesisWorks/hypothesis/pull/643#issuecomment-307719092) however I've found code such as the below to not add much:

```python
class TestThing:

    @given(param1=infer, param2=infer)
    def TestFacetOfThing(self, param1: float, param2: float) -> None:
        assert check_facet_of_thing_works(param1, param2)
```

I've therefore written a little decoration which passes `infer` to all of the arguments of the test method and it looks a little tidier and less repetitive, particularly when there are lots of methods:

```python
class TestThing:

    @given_inferred
    def TestFacetOfThing(self, param1: float, param2: float) -> None:
        assert check_facet_of_thing_works(param1, param2)
```

Secondly given I make extensive use of `register_type_strategy` I've written another small annotation which means that instead of `conftest.py` looking like:

```python
@pytest.fixture(scope="session", autouse=True)
def _register_types(request):
    register_type_strategy(np.float64, make_float)
    register_type_strategy(MyType, make_m_type)

def make_float(typ: Type) -> SearchStrategy[np.float64]:
        from_dtype(np.dtype(typ))
            .filter(lambda x: not np.isnan(x))
            .filter(lambda x: not np.isinf(x))
            .filter(lambda x: x < mx)

def make_my_object() -> SearchStrategy[MyObject]:
    # fancy strategy for my object
```
One can instead write:

```python
@pytest.fixture(scope="session", autouse=True)
def _register_types(request):
    TypeStrategy.register_types()

@TypeStrategy
def make_float(typ: Type) -> SearchStrategy[np.float64]:
        from_dtype(np.dtype(typ))
            .filter(lambda x: not np.isnan(x))
            .filter(lambda x: not np.isinf(x))
            .filter(lambda x: x < mx)

@TypeStrategy
def make_my_object() -> SearchStrategy[MyObject]:
    # fancy strategy for my object
```

And the `TypeStrategy` decoration will register the function to the return type specified by the type annotation. This doesn't add much in this small example, but if there are numerous strategies then this cleans things up a little bit.

These both sit very stand-alone so I can quite happily keep them in a little `utils` package and reuse them (or even release them) like that, however, I showed them to a chap at work and he thought they were cool enough that you might want to include them in Hypothesis. I shan't be offended at all either way - opinions and comments are most welcome.

**Comment by Zac-HD** [comment]
Hey Richard - thanks for getting in touch!  We always love hearing from users, especially when they're happy and doing such cool things :grin: 

For the first item, I think `@given_inferred` is probably best off staying in your utils directory (and many others, I'm sure).  While useful, it's also dangerous to add to `@given` because of the interactions with e.g. pytest fixtures.  Since it's reasonably easy to implement, I think the benefits of keeping a simple and minimal API mean that we should leave it out.

For the second idea, I'd be pretty happy to have `@st.register_type_strategy` work!  The implementation would have to be a little fiddly, but we can handle that I'm sure.  (also: check out [`np.isfinite()`](https://numpy.org/doc/stable/reference/generated/numpy.isfinite.html), or better yet the `from_dtype()` upgrades in #2619!)

```python
# This is example code to illustrate my ideal API.

@st.register_type_strategy
def make_float(typ: Type) -> SearchStrategy[np.float64]:
        return from_dtype(np.dtype(typ), allow_nan=False, allow_infinity=False)filter(lambda x: x < mx)

@st.register_type_strategy
def make_my_object() -> SearchStrategy[MyObject]:
    ... # fancy strategy for my object

@st.register_type_strategy
@st.composite
def make_foos(draw, typ: Type[Foo]) -> Foo:
    # This should also work - we might need to teach @st.composite
    # how to modify the return-type annotation though.
    return draw(...)
```

When used as a decorator, `st.register_type_strategy` should check that the first argument is callable and not a type, that the second argument is `not_set` (internal constant), and that the return-type-annotation is `SearchStrategy[T]`. If the first argument is annotated but not with `type` or `Type[T]`, error. We should then register for `T` the result of calling the function (if no args), or the function itself. Finally we return the function so that it can be called normally and e.g. passed to `@given` or `st.builds()`.

Perhaps you'd be up for writing a PR or two to implement it?  Our usual offer of "we'll help write the patch" applies obviously, so feel free to open a PR well before it's finished and we'll do however many rounds of review it takes with a smile :smile:

**Comment by rvodden** [comment]
Hey @Zac-HD - Thanks for the super-fast response! I'll have a bash and, as you say, raise a PR long before it's ready to be merged. I'll also pinch your nicer `make_float` :-)

**Comment by Zac-HD** [comment]
Hey @rvodden - any progress on this one?  If you've moved on I'm inclined to close the issue.

**Comment by rvodden** [comment]
Sorry a few personal issues have got in the way. I have made a start, but if you'd like to keep your board clean I suggest you close it and I can reopen it when life gets a little simpler.

**Comment by Zac-HD** [comment]
Sure - PR welcome when you're ready 😊
