### ISSUE TITLE
Integration with icontract?

### ISSUE THREAD

**Issue by mristin** [HypothesisWorks/hypothesis#2679]
Hi,
I'm the maintainer of https://github.com/Parquery/icontract, a design-by-contract library for Python 3. Unlike other contract libraries in Python (*e.g.*, [dpcontracts](https://github.com/deadpixi/contracts) and [deal](https://github.com/life4/deal), icontract supports behavioral subtyping, which is important in many practical scenarios where object-oriented code is used.

Would you be interested to integrate icontract somehow with Hypothesis, so that the contracts can be taken into account automatically? This would be a great benefit for tightly-contracted code as tests could be effortlessly generated while the documentation would remain formal and succinct.

I'm not totally sure what the easiest and most efficient path would be. Usually people write quite relaxed contracts, so the test space becomes huge while the developer would probably prefer to test only a subspace. One approach I thought of was to introduce code generation and automatically generate code which uses Hypothesis, so that the developer can manually tight up the constraints for Hypothesis testing.

Or maybe we start by integrating icontract directly with Hypothesis (similar to how you integrated dpcontracts, see PR #1565)? If we go that way, I think that it would be important to somehow translate the contracts into hints for Hypothesis whenever possible. The integration with dpcontracts basically performs a kind of rejection sampling where you hit & discard samples depending on contract rejection. I doubt that this works efficiently in practice. However, to start somewhere, maybe I could try to come up with a plug-in ("extra") for icontract akin to https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/dpcontracts.py?

What do you think?

**Comment by Zac-HD** [comment]
Hey @mristin!  Thanks for getting in touch - I'm definitely keen to support good integration between Hypothesis and icontract; the only questions are how and where the code should live.  Plausible answers:

- Hypothesis now has enough hooks (e.g. entry points) that pretty much everything could live in the icontracts package.  That's probably a better design, since it makes updates on your end easier, but I'm not opposed to adding `hypothesis.extra.icontract` either.
- `builds()` and `from_type()` integration seems sensible, probably along with something like the `dpcontracts` extra.
- We can probably think of other things too; I'll read up in more detail in the next few days.

I'm in UTC+11, so send me an email with a time next week in the Zurich morning which works for you and we can chat?

**Comment by Zac-HD** [comment]
Our conversation suggested two concrete ideas to pursue, both as part of a new `icontract[hypothesis]` extra:

- Shipping a `from_icontract(callable, /, *args, **kwargs)` function, which works like `st.builds()` but with extra knowledge of contract preconditions.  Note that this *can't* be done entirely based on single arguments, because contracts can include relationships between multiple inputs, input and output, etc.
- Something like the `hypothesis.extra.dpcontracts.fulfill()` decorator.  Note that `icontract` could be much more precise: instead of rejecting examples which fail any precondition, it could reassign the `__precondition__` function to call `hypothesis.reject()` on failure.  Internal precondition violations would then continue to make the test fail.

Longer term, i.e. after those have been shipped, we're also interested in investigating integration with the Ghostwriter, and [using Hypothesis to integrate with Crosshair](https://gist.github.com/Zac-HD/28a81c7fc9c73637eba4b2f675bb3b5a).  Those can have new issues when we're ready to work on them though :grin:
