### ISSUE TITLE
Use `__source_code__` in `extract_lambda_source`

### ISSUE THREAD

**Issue by mristin** [HypothesisWorks/hypothesis#2713]
Hypothesis currently uses `inspect.getsource()` in `hypothesis.internal.reflection.extract_lambda_source(.)` when inspecting lambdas passed into the `filter`. Unfortunately, this does not work if a third-party library creates lambdas on-the-fly in memory using `compile` built-in function as `inspect.getsource()` needs the source code to exist on disk.

Would it be possible for Hypothesis to check first if the function contains a dunder such as `__source_code__` or something similar before resorting to `inspect.getsource()`? I circumvented the problem by inheriting from `FilteredStrategy` and overriding the `__repr__` method:

```
class _FilteredStrategyWithAttachedSourceCode(
    hypothesis.strategies._internal.strategies.FilteredStrategy):

    def __repr__(self):
        """Represent the filtered strategy with the supplied condition representation."""
        if not hasattr(self, "_cached_repr"):
            self._cached_repr = "%r%s" % (
                self.filtered_strategy,
                "".join(
                    ".filter(%s)" % (
                        cond.__source_code__ if hasattr(cond, '__source_code__')
                        else hypothesis.internal.reflection.get_pretty_function_description(cond))
                    for cond in self.flat_conditions
                ),
            )
        return self._cached_repr
```
I also did the same with a `map` strategy:
```
    class _Strategy(
        hypothesis.strategies._internal.strategies.MappedSearchStrategy):
        """Override representation of the mapped search strategy to highlight the type."""

        def __repr__(self) -> str:
            """Represent the strategy with hi"""
            if not hasattr(self, "_cached_repr"):
                self._cached_repr = "%r.map(%s)" % (
                    self.mapped_strategy,
                    'lambda d: {}(**d)'.format(a_type.__name__),
                )
            return self._cached_repr
```

Since both `FilteredStrategy` and `MappedSeachStrategy` are internals, it would be preferrable to have this functionality integrated upstream somehow.

I also thought about creating a temporary file to store the source code, but this has many complex implications (garbage collection, management of the source code becomes a pain when new code is added *etc.*).

**Comment by Zac-HD** [comment]
Is there an existing standard or convention for this?  I'm open to supporting it regardless, but inventing dunder conventions is discouraged due to the possibility of e.g. collisions with future changes to the language.  And unlike e.g. Numpy's `__array_foo__` conventions, any reasonably clear name like `__source_code__` is a pretty clear candidate for later use by the language core developers.

As an alternative, I'd like to propose an optional dependency on [`uncompyle6`](https://pypi.org/project/uncompyle6/) to recover source code from the bytecode object stored as `__code__`.  For example:

```python
import inspect
import io
import uncompyle6

ns = {}
exec(compile("f = lambda x: x >= 2", "<string>", "exec"), ns)
f = ns["f"]

assert f(2) is True
assert f(1) is False

# inspect.getsource(f)  # raises OSError: could not get source code

source = uncompyle6.deparse_code2str(f.__code__, out=io.StringIO())
body = source.rstrip().replace("return ", "")
sig = str(inspect.signature(f))[1:-1]

print(f"lambda {sig}: {body}")
```

If this is sufficient for your use-case I'd even prefer to omit the other option, because decompilation handles cases like missing or inaccessible source files in addition to runtime use of `compile`.

**Comment by mristin** [comment]
I had problems with `uncompyle` when I developed [icontract](https://github.com/Parquery/icontract) originally since it did not cover all the language features (the development lagged behind the Python development). I haven't tested it extensively, but I my gut feeling is that it is not a viable route.

I am not aware of any standard and agree that `__source_code__` is a name with potential conflict. I'll use monkey patching for the time being. I suppose monkey patching would also reflect (no pun intended) in the code that tries to optimize the filtering strategies?

**Comment by Zac-HD** [comment]
[Also we've tried decompiling before](https://hypothesis.readthedocs.io/en/latest/changes.html#v3-6-0), and all the tools are GPL-licenced which means we can't depend on them from Hypothesis 😢  So doubly non-viable.

Yep, whatever filtering code we write is very likely to go via `extract_lambda_source()` for lambdas, so monkeypatching it should work well.

Closing this issue because I honestly think that monkeypatching is the best option here - not that it's great, but providing any kind of deliberate hook for this seems worse 😕
