### ISSUE TITLE
Canonical way to de/serialize settings from JSON-able data

### ISSUE THREAD

**Issue by mristin** [HypothesisWorks/hypothesis#2714]
(Please apologize if this has been already implemented. I couldn't find any reference though I search the past issues as well as read the documentation, notably https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.load_profile.)

What would be the canonical way to de/serialize Hypothesis settings from JSON-able data? 

I need to pass it into my command-line tool (see [this snippet](https://github.com/mristin/icontract-hypothesis/blob/a59a14795aa13301f00557cc25918a004fe222d0/icontract_hypothesis/pyicontract_hypothesis/_test.py#L69)) which is later passed through by a Vim plugin (see [this snippet](https://github.com/mristin/icontract-hypothesis-vim/blob/ac0ec5ec6a9bd681e19bcd549e0ae4e209028701/plugin/icontract_hypothesis.vim#L41)) and eventually a Pycharm plug-in will provide GUI for choosing the settings as well.

Obviously, some settings can not be serialized to/from JSON (such as `database`), but most numeric values as well as enums and collections of enums can. It would be great if there is a single function or at least a protocol to follow which the users can readily use instead of reinventing their own (buggy and non-standard) ones.

**Comment by Zalathar** [comment]
Hmm. Currently our approach to data-driven settings is to provide useful APIs, but leave the actual integration up to ad-hoc user code or third-party packages. So there would be a high bar to adding this sort of feature to Hypothesis itself.

That said, I can also see a maintenance advantage in having some first-party way to coerce string-ish or JSON-ish data into proper values, since the metadata needed to do that reliably is already mostly present in our core settings code anyway.

Or perhaps it would be sufficient to expose enough officially-supported metadata that a reliable third-party converter becomes mostly trivial. Most of our settings are booleans, numbers, strings, enums, or lists-of-enums, all of which seem pretty tame for a metadata-driven converter.

(I'm not really familiar with how people usually introspect types or unmarshall JSON in the Python ecosystem, so I'm not sure what this might look like concretely.)

**Comment by Zalathar** [comment]
The work already done in #2690 should be handy here.

**Comment by Zac-HD** [comment]
> Most of our settings are booleans, numbers, strings, enums, or lists-of-enums, all of which seem pretty tame for a metadata-driven converter.

With the two exceptions of `deadline` (serialise as number of milliseconds) and `database` (perhaps a `[qualname, *args]` list?), that's everything.

A fairly simple [`default` method on a JsonEncoder subclass](https://docs.python.org/3/library/json.html#json.JSONEncoder.default) could handle these types, and I'd suggest having a two-stage "deserialise JSON, then convert to enums" deserialise pass - there are only `Verbosity`, `Phase`, and `HealthCheck` enums after all.  [`Enum.__members__`](https://docs.python.org/3/library/enum.html#iteration) would also let you skip the dictionaries you create; [enums are also callable and indexable](https://docs.python.org/3/library/enum.html#programmatic-access-to-enumeration-members-and-their-attributes).

```python
class J(JSONEncoder):
     def default(self, o):
         if isinstance(o, timedelta):
             return o.total_seconds() * 1000
         if isinstance(o, Enum):  # maybe we should make HealthCheck an IntEnum so this is automatic?
             return o.value
         return super().default(o)  # error if you passed non-None parent or database
```

**Comment by Zalathar** [comment]
(By the way, I noticed that the docs for `database` setting claim that it accepts DB path strings or the string `":memory:"`, but the implementation doesn't actually permit these. I'm preparing a quick doc-fix patch to clear this up.)

**Comment by mristin** [comment]
> I'd suggest having a two-stage "deserialise JSON, then convert to enums" deserialise pass

I think the second stage is the only feature that needs to be standardized in Hypothesis (that's also what I meant with "JSON-able"). The downstream users can then freely choose what actual format they use (JSON, YAML, XML *etc.*).

**Comment by Zac-HD** [comment]
```python
def convert_settings_kwargs_from_jsonable(kw: Dict[str, Any]) -> Dict[str, Any]:
    kw["verbosity"] = hypothesis.Verbosity(kw["verbosity"])
    kw["phases"] = [hypothesis.Phase(k) for k in kw["phases"]]
    kw["suppress_health_check"] = [
        hypothesis.HealthCheck(k) for k in kw["suppress_health_check"]
    ]
    return kw
```

Does that really need to live upstream?

**Comment by mristin** [comment]
I suppose you'd like to add error messages to it (*e.g.*, indicate the relative path where the error ocurred). There are also validators which were omitted here (+relative path of the error) *etc.*

Please let me know if you'd like me to create a PR for it.

**Comment by mristin** [comment]
P.S. maybe I did not explain the use case well. I imagine tools that interact with Hypothesis which can all rely on standardized specification of the settings that is evolved in sync with the library.

For example, a JSON schema would already cover most of the use cases (even non-Python ones). For me it makes sense that the specs live within Hypothesis (as schema and/or validation code), but of course I also see that it can be considered bloat or unnecessary.

For example, when a new version of Hypothesis introduces new settings, the third-parties can support them out-of-the-box.

**Comment by Zac-HD** [comment]
I think that we should not include this logic upstream, at least for now.

- Settings are both stable and simple, so if we're not designing for forward-compatibility it's easy to handle enums downstream (as above)
- If we *are* going to think about compatibility, this is a whole new API surface to maintain, and that's pretty painful - for example I'd want to use strings rather than integers as enum values (self-documenting and avoids the [value-reuse problem](https://developers.google.com/protocol-buffers/docs/proto3#reserved))... and then we'd need a whole extra deprecation cycle.
- Providing a schema means a second source of truth, which we *really* don't want to deal with.

**Comment by Zalathar** [comment]
While it's valid and reasonable to want this feature, I agree that Hypothesis itself should not add it at this time.

If there's enough interest, it should be possible to write a mostly future-proof third-party module that introspects on the declared argument types of `settings`, and uses those to automatically convert enums and lists-of-enums.

If that catches on as a de-facto standard, then we can reassess whether to make stability guarantees for that metadata, or whether to incorporate it as a first-party feature.

**Comment by mristin** [comment]
Good, I'll keep the logic in my package. 

In case somebody needs a copy/paste solution: https://github.com/mristin/icontract-hypothesis/blob/22aa95c9cf56ec74f2d6a48ec0024f7e8d76362b/icontract_hypothesis/pyicontract_hypothesis/_test.py#L69

If there is need, I can also make a separate PyPI package, just ping me on this issue.
