### ISSUE TITLE
Turn pytest function-scoped fixtures into a health check error (instead of a hard error)

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#2733]
As I mentioned in https://github.com/HypothesisWorks/hypothesis/issues/2709#issuecomment-753732671, I'm thinking about adding a health check for function-scoped fixtures, so that rare intentional uses can continue to opt-out when the warning becomes an error (e.g. #2731)

(Context: Using pytest function-scoped fixtures with `given` is almost always a bad idea, because the fixtures only run once for the whole function, and are not reset between individual examples.)

Implementing this is slightly annoying, because our pytest plugin doesn't have convenient access to the actual settings object that will be used by the underlying test. Currently my plan is to have the plugin continue to generate a warning/error message, but instead of calling `note_deprecation`, it will merely stash the message in a `_hypothesis_internal...` property of the test. Then I'll add a check in `given`/`wrapped_test` (near the existing `not_a_test_method` check) that will pull out the stashed message and pass it to `fail_health_check`, which will raise an error or silently do nothing as appropriate.

The main questions I have right now are:

- Should we actually preserve the opt-out?
  - If we do ever get proper per-example fixture support, it will be a breaking change for anybody relying on the opt-out, which is awkward (and presumably one of the motivations behind the error).
  - On the other hand, this doesn't seem likely to happen in the foreseeable future.
  - Aside from compatibility, it could be argued that having a convenient opt-out would lead to more harm than good, if people use it to silence a pesky error without understanding the actual problem.
  - I'm inclined not to worry about this too much.

- Is a health check the right mechanism?
  - Adding a pytest-specific health check is arguably a layering violation, though in practice I think it's fine.
  - In https://github.com/HypothesisWorks/hypothesis/issues/2731#issuecomment-753561077, @Zac-HD proposed a `@pytest.mark.hypothesis_function_scoped_is_fine` annotation to achieve the same result in a different way.
  - Using the existing health-check mechanism seems better to me, since it's a good fit for the semantics of health checks (severe enough to be an error by default, but there are legitimate reasons to opt out).

- Is it OK to roll this change into our annual major version bump, assuming I have a suitable patch in good time?

**Comment by Zac-HD** [comment]
I agree that this should be a health check rather than an unconditional error, and that allowing opt-out is OK since there is a legitimate interest in doing so.  I'm not at all attached to using a pytest mark, that's just what I thought of off-hand and I prefer the healthcheck idea.

I'm happy to make it part of our major version bump, **but** I'd actually rather ship it early - for now the setting allows you to silence the *deprecation warning*, and then we upgrade that to a health check error in 6.0 as scheduled.  It's also fine if someone does eventually contribute or fund fixture integration; we just remove the healthcheck error and deprecate that enum entry.
