### ISSUE TITLE
Frequent release schedule causes update madness

### ISSUE THREAD

**Issue by ahesford** [HypothesisWorks/hypothesis#2747]
What is going on with the release schedule of this repository? It looks like new releases are cut daily. This seems to undermine the concept of a "release" as a reasonably tested point of stability.

Can you recommend a version sequence that we can track in Void Linux that provides reasonable stability with a less-than-daily update cycle?

Thanks.

**Comment by Zac-HD** [comment]
Instead of using time-based releases, we automatically tag each merged change as a new version.  https://hypothesis.works/articles/continuous-releases/ describes this in more detail, but in short we find that:

- this has made releasing much easier (and less error-prone) for our all-volunteer team
- users get bugfixes or new features immediately - especially useful if they contributed the patch
- the package is *better tested* as a result - because we insist that every PR is ready-to-ship, we never rely on the "we'll fix that later" which rarely happens in practice

As it happens, this as led to more frequent releases over the last week or so because a few of us have had time to merge longstanding PRs, fix old issues, and generally prepare for a major release.

The other point is the concept of a "release sequence": in short, we don't have the resources to support that.  Hypothesis therefore responds to any bugs or other issues in the latest release **only**, and our only response is to create a new latest release by incrementing the patch, minor, or major version number as per semver.

If our releases are too frequent for you, we suggest either:

- automating your downstream packaging so you can keep up ([here's our documented advice for downstream packagers](https://hypothesis.readthedocs.io/en/latest/packaging.html))
- updating to the then-latest release on a schedule that suits you, e.g. weekly.  This is what we recommend for most end users.

I hope that helps.

**Comment by abenson** [comment]
> this has made releasing much easier ... for our ... team

> users get bug[s]... immediately

> the package is better tested as a result

You literally just said its released without testing?

**Comment by Zac-HD** [comment]
> You literally just said its released without testing?

No, I said that *every pull request is tested as if for release* (and then *is* released).  For more information, see:

- https://github.com/HypothesisWorks/hypothesis/blob/master/guides/testing-hypothesis.rst
- https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python/tests
- https://github.com/HypothesisWorks/hypothesis/actions
