### ISSUE TITLE
Hypothesis breaks my random number generator

### ISSUE THREAD

**Issue by awildtechno** [HypothesisWorks/hypothesis#2871]
Hi! I'm looking to integrate Hypothesis into an existing codebase. The code is old and tests are running in pytest and saving to a local database which is not flushed. We already use existing a lot of random numbers/choices and I'd rather not convert a thousand tests to hypothesis in the middle of a feature release.

It looks like Hypothesis is reusing the same seed for multiple runs of the test, resulting in errors where the something like a phone number or email with a unique key gets generated with exactly the same value twice.

Is there a way to turn off the RNG seeding control completely? The only thing I could find was to explicitly hunt down every random call and replace `random` with an instance of `random.Random()`.

hypothesis==4.38.1

**Comment by Zac-HD** [comment]
Varying the global random seed with [`st.random_module()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.random_module) wouldn't actually help you, since I think this is about Hypothesis' generation rather than the global RNG.

> The tests are saving to a local database which is not flushed. ... resulting in errors where the something like a phone number or email with a unique key gets generated with exactly the same value twice.

You will need to fix thisbefore you can use Hypothesis effectively.  There is no workaround; "each test case can be replayed to get the same behaviour" is a core requirement for shrinking or even just replay to work.

Having a context manager to reset the database between each test case might be somewhat slower, but deterministic tests are definitely worth it.

> hypothesis==4.38.1

Can I also recommend updating?  This version is almost two years old, and we've had substantial performance improvements and new features since then!

**Comment by awildtechno** [comment]
Thanks for the quick reply. That makes sense and I had a feeling it was the case. I'll work on refactoring the test suite but I was hoping there was an easy side door.
