### ISSUE TITLE
Mind inheritance when inferring TypedDict-based class

### ISSUE THREAD

**Issue by Melevir** [HypothesisWorks/hypothesis#2876]
This one continues #2872.

Here is a reproducible example:

```python
class SomeData(TypedDict):
    a: str
    b: int

class SomeMoreData(SomeData):
    c: List[int]

register_type_strategy(SomeData, builds(SomeData, a=just('string from strategy'), b=just(42)))

@given(from_type(SomeMoreData))
def test_some_data(item):
    assert item.a == 'string from strategy'
    assert item.b == 42
```

For now, the test will fail, but it make sense to mind inheritance when inferring TypedDicts types.

If the proposition (or bug, whatever) is approved, I'll try to implement the thing.

**Comment by Zac-HD** [comment]
I'll call this an "enhancement", and would be happy to have the feature.

But be careful!  You'll need to traverse the MRO, use the closest registered supertype for all fields defined on that type (handling the case where the registered strategy doesn't return a dict...), and then use our current logic to resolve the fields added by subclasses of whatever was registered down to the type we're actually constructing.

Tricky, but doable 😁

**Comment by sobolevn** [comment]
There's an ongoing `PEP` discussion that might be related: https://mail.python.org/archives/list/typing-sig@python.org/thread/53XVOD5ZUKJ263MWA6AUPEA6J7LBBLNV/ But, since Guido is the PEP's sponsor - it is a matter of time.

Maybe there are some things to consider from it in the current implementation.

**Comment by Zac-HD** [comment]
Gosh... looks kinda ugly to me, but then I've never felt that `TypedDict` is really idiomatic for statically-typed-Python.  If you're going to this much trouble to annotate your dicts, maybe just use a dataclass?

In any case, I'd hope that at runtime this will just use the existing attributes for lists of optional and required keys (see https://github.com/python/cpython/pull/17214); in which case it will "just work" with Hypothesis.

**Comment by gwerbin** [comment]
> Gosh... looks kinda ugly to me, but then I've never felt that `TypedDict` is really idiomatic for statically-typed-Python. If you're going to this much trouble to annotate your dicts, maybe just use a dataclass?
> 
> In any case, I'd hope that at runtime this will just use the existing attributes for lists of optional and required keys (see [python/cpython#17214](https://github.com/python/cpython/pull/17214)); in which case it will "just work" with Hypothesis.

`TypedDict` is really useful for interacting with untyped code that's outside your control, or data that's been deserialized to a dict (or list of dicts) from external sources, and where it might not make sense to instantiate new objects at runtime.

I'm actually glad this issue is here, because i just wrote a bunch of `@composite` strategies to generate a bunch of data to simulate database query results, like this:

```python
from typing import List, TypedDict
from hypothesis strategies import SearchStrategy, composite, integers, lists, text

class FooDict(TypedDict):
    a = int
    b = str

class BarDict(TypedDict):
    c = int
    d = List[FooDict]

@composite
def foos(draw: SearchStrategy) -> FooDict:
    return {
        "a": integers(),
        "b": text(),
    }

@composite
def bars(draw: SearchStrategy) -> BarDict:
    return {
        "c": integers(),
        "d": lists(foos()),
    }
```

If I understand the issue here, it's that `from_type` won't correctly resolve `BarDict` as a subtype of `FooDict`? If so, I guess I will stick to that technique for now, but hopefully I can dispense with all these strategy definitions in the future and just use `from_type`. At least now you have a tangible use case :)

**Comment by Zac-HD** [comment]
Unfortunately, it turns out that [the `TypedDict` implementation](https://github.com/python/cpython/blob/f4095e53ab708d95e019c909d5928502775ba68f/Lib/typing.py#L2366-L2423) simply doesn't retain inheritance information at runtime, so we won't be able to support this feature.

I was keen enough to try parsing, but `inspect.getsource()` *also* fails!

**Comment by sobolevn** [comment]
@Zac-HD I think it is worth filling a BPO issue. Maybe even two:
- `inspect.getsource()` should not fail
- getting base classes should also be somehow possible, otherwise it totally kills introspection

I've seen lots of bugs with `TypedDict` in terms of its creation / metaclass usage / etc. Many related PRs were accepted.

**Comment by Zac-HD** [comment]
Yeah, probably... I just don't have the energy for another long engagement with python-dev at the moment, and once I do it'll be about getting PBT running in their CI.

**Comment by sobolevn** [comment]
Yes, I've seen this thread about hypothesis in CPython's CI. Sending hopes and prayers, really cool feature 🙏 

I will open them in this case 🙂

**Comment by sobolevn** [comment]
I am filling a BPO issue right now and I found that the original proposal by @Melevir is not what I would expect from hypothesis.

Let's see how regular classes work on this case:

```python
from typing import List
from hypothesis import given, strategies as st
from dataclasses import dataclass

@dataclass
class SomeClass:
    a: str
    b: int

@dataclass
class SomeMoreClass(SomeClass):
    c: List[int]

st.register_type_strategy(
    SomeClass, st.builds(SomeClass, a=st.just("string from strategy"), b=st.just(42))
)

@given(st.from_type(SomeMoreClass))
def test_some_class(item):
    assert item.a == "string from strategy"
    assert item.b == 42
```

This will fail with:

```
__________________________________ test_some_class ___________________________________

    @given(st.from_type(SomeMoreClass))
>   def test_some_class(item):

ex.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

item = SomeMoreClass(a='', b=0, c=[])

    @given(st.from_type(SomeMoreClass))
    def test_some_class(item):
>       assert item.a == "string from strategy"
E       AssertionError: assert '' == 'string from strategy'
E         - string from strategy

ex.py:36: AssertionError
-------------------------------- Captured stdout call --------------------------------
Falsifying example: test_some_class(
    item=SomeMoreClass(a='', b=0, c=[]),
)
```

Why the same should work for `TypedDict`?

**Comment by sobolevn** [comment]
@Zac-HD I was also not successful in reproducing `inspect.getsource` failure.

This works for me:

```python
from typing import TypedDict
import inspect

class SomeData(TypedDict):
    a: str
    b: int

class SomeExtraData(SomeData):
    c: bool

print(inspect.getsource(SomeData))
print(inspect.getsource(SomeExtraData))
```

<img width="752" alt="Снимок экрана 2021-12-26 в 13 58 43" src="https://user-images.githubusercontent.com/4660275/147406007-c2d13e62-965d-4b4c-960d-54f75108d7d3.png">

Is there anything that I am missing?

**Comment by Zac-HD** [comment]
Huh, looks like `inspect.getsource()` works for `TypedDict` on Python 3.8 and later!  (I'm still not keen to rely on this though...)

I think that `TypedDict` is a bit special / different to standard classes here, but on reflection that you're also right that we probably don't want this feature - it's pretty hard to say why e.g. dataclasses should follow either standard classes or typeddicts, and in that case we should default to treating them all the same (i.e. status quo).

And also, thanks again for following this up!  It's fantastic to have your independent investigations and design work on this stuff 😍
