### ISSUE TITLE
Add helpful error message for `st.sampled_from(EmptyEnumWithAnnotations)`

### ISSUE THREAD

**Issue by BrendanJM** [HypothesisWorks/hypothesis#2923]
Following the discussion at #2693, the documented method of sampling from an Enum does not appear to work (or the documentation could use clarification and/or an example). The approach I tried is:

```python
from enum import Enum
from hypothesis import given, strategies as st

class MyEnum(Enum):
    a: 'a'
    b: 'b'

@given(st.sampled_from(MyEnum))
def test_example(instance):
    assert True
```

This raises `hypothesis.errors.InvalidArgument: Cannot sample from a length-zero sequence.` Additionally, `sampled_from(list(MyEnum))` raises the same issue. Hypothesis version is 6.8.5, python is 3.9.2

**Comment by BrendanJM** [comment]
For context, the end goal I'm looking to achieve is generating Pydantic model, with some attributes being enums: https://pydantic-docs.helpmanual.io/hypothesis_plugin/

**Comment by Zac-HD** [comment]
Your problem here is that `MyEnum` *doesn't have any elements*, because you've used annotations instead of assigning them.  Replace `:` with `=`, and it'll work 🙂

This is a weird enough edge case that I didn't spot it immediately though, so I think we should upgrade `st.sampled_from()` to check `vars(MyEnum).get('__annotations__')` if `list(MyEnum) == []` and raise an error that can explain what's happening.

**Comment by BrendanJM** [comment]
Well that's embarrassing - good catch, and thanks for the quick response!
