### ISSUE TITLE
`@settings(phases=)` API makes it very easy to accidentally enable `Phase.explain`

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#2989]
Pop quiz, what does this line of code do?

```python
@settings(phases=set(Phase) - {Phase.target})
```

If your answer didn't include “enables explain mode, potentially making test runs and failure-reporting *much* slower”, then perhaps you see the problem.

---

I think there are two issues here:

- 9X% of the time, `phases` is used for *excluding* phases, yet the common idiom for doing so is quite clunky (and often incorrect if your current profile deliberately excludes some phases).
- Having an expensive off-by-default phase makes the above incorrectness problem all but guaranteed, with potentially severe consequences.

---

I therefore tentatively propose two changes:

- Add some kind of `skip_phases` setting, making it much easier to write correct code that excludes phases without accidentally enabling others.
- Don't enable the explain-tracer and explainer on the basis of `Phase.explain` alone; require explicit opt-in via a separate setting.

**Comment by Zalathar** [comment]
See https://github.com/HypothesisWorks/hypothesis/pull/2981/commits/eb271787fbb8e86e33ead94cb5182e32790a7a24 for a recent example of this actually happening.

Note that if I artificially add a failing assert to that test, the time taken to actually report failure jumps from ~20 seconds (without explain) to ~3 minutes (with explain).

**Comment by Zac-HD** [comment]
I think this is an important thing to get right, but I'd much rather take longer to think about it if that means we can change it *once* to a design that we'll be happy with for the long term.  In particular, I'm concerned that adding a `skip_phases` setting would lead to the same unintuitive and ambiguous behaviour that we saw from the `suppress_health_check` and [(now removed) `perform_health_check `](https://hypothesis.readthedocs.io/en/latest/changes.html#v3-56-0) setting.

I'm also not quite convinced that this is hurting projects which aren't Hypothesis or direct extensions - the only downstream uses I've seen for the `phases` setting are `phases={Phase.explain}` to disable all but explicit examples, and `phases=set(Phase) - {Phase.shrink}` to disable shrinking.  In the former case there's obviously no problem; and in the latter case explain-mode is also disabled because it only applies while shrinking a failing example.

The main reason that I made `explain` a phase in the first place was that it interacts with `shrink` in roughly the same way that `target` does with `generate` - the latter builds on the former.  Using the existing semantics for phases means avoiding the mess of handling potentially-conflicting settings for "explain without shrinking".

Performance idea: make the `Tracer` class faster - using `__slots__`, reducing attribute lookups, maybe not-tracing some files.  Unfortunately all my other performance ideas are prone to breaking in subtle ways and therefore *not* a UX improvement.

**Comment by Zalathar** [comment]
> I'm also not quite convinced that this is hurting projects which aren't Hypothesis or direct extensions - the only downstream uses I've seen for the `phases` setting are `phases={Phase.explain}` to disable all but explicit examples, and `phases=set(Phase) - {Phase.shrink}` to disable shrinking. In the former case there's obviously no problem; and in the latter case explain-mode is also disabled because it only applies while shrinking a failing example.

Ah, that sounds plausible. And I hadn't noticed that the tracer only gets installed after at least one failure.

(Actually, how does this interact with the continue-after-failure feature? Is it possible to disable shrinking, accidentally enable explaining, and then have the explainer decide to run on just the examples between the first failure and the cutoff?)

**Comment by Zac-HD** [comment]
> Actually, how does this interact with the continue-after-failure feature? Is it possible to disable shrinking, accidentally enable explaining, and then have the explainer decide to run on just the examples between the first failure and the cutoff?

Yes, that's exactly what would happen.  Though I'd intended explain mode to only run during shrinking, so maybe we want to change that?

(Perhaps we should also disable it for tests which are failing due to a deadline; both to avoid masking the real perf issue and because pointing to a point on the control-flow graph is less likely to be helpful)
