### ISSUE TITLE
Implement Ghostwriter for dunder methods

### ISSUE THREAD

**Issue by ligurio** [HypothesisWorks/hypothesis#3013]
Python allows to implement certain operations for a class that are invoked by special syntax by defining methods with special names [1]. This is Python’s approach to operator overloading, allowing classes to define their own behavior with respect to language operators. For instance, if a class defines a method named `__eq__()`, and x is an instance of this class, then x can be compared with another instance using operator `==`. According to this I believe it would be useful to have a strategy that checks properties for default class methods. For example if `a` and `b` have method `__eq__()` then a pair of two instances should hold a properties `(a == b) == (b == a)` and `(a == b) ~= (a ~= b)`, for method `__lt` should hold a property `(a > b) == (b < a)` and so on.

1. https://docs.python.org/3/reference/datamodel.html#special-method-names

Some methods and their properties:

### Numeric operations

- `object.__add__(self, other)`
  - `a + b == b + a`
- `object.__sub__(self, other)`
- `object.__mul__(self, other)`
  - `a * 2 == a + a`
  - `a * 1 == a * 1 * 1`
- `object.__matmul__(self, other)`
  - ?
- `object.__truediv__(self, other)`
  - ?
- `object.__floordiv__(self, other)`
  - ?
- `object.__mod__(self, other)`
  - ?
- `object.__divmod__(self, other)`
  - ?
- `object.__pow__(self, other[, modulo])`
  - ?
- `object.__lshift__(self, other)`
  - ?
- `object.__rshift__(self, other)`
  - ?
- `object.__and__(self, other)`
  - ?
- `object.__xor__(self, other)`
  - ?
- `object.__or__(self, other)`
  - ?

### “rich comparison” methods

- `object.__lt__(self, other)`
  - `(a > b) == (b < a)`
- `object.__le__(self, other)`
  - `(a >= b) == (b <= a)`
- `object.__eq__(self, other)`
  - `(a == b) == (b == a)`
  - `(a == b) ~= (a ~= b)`
- `object.__ne__(self, other)`
  - ?
- `object.__gt__(self, other)`
  - ?
- `object.__ge__(self, other)`
  - ?

**Comment by Zac-HD** [comment]
Terminology note: "strategy" is the thing-that-we-generate-examples-with; [the Ghostwriter](https://hypothesis.readthedocs.io/en/latest/ghostwriter.html) is how we automatically write tests based on known patterns (i.e. properties).

As I understand it, you're proposing that when the Ghostwriter is pointed at a custom class, it should write tests for known properties of whatever special ("dunder") methods it defines.  This would include

- associativity and commutativity of arithmetic operations (like our existing `--binary-op` ghostwriter)
- various equivalences, such as `x * 2 == x + x` or `x **2 == x * x`
- identities like `x * 1 == x`

I would be happy to *consider* a PR for this, and likely to merge it, but I have way too much else on to write it myself.  I'd be happy to review and assist too, because I can also imagine that if it works only in a narrow range of circumstances I might not merge it - the Ghostwriter is for teaching generally-useful features and design patterns, not just automation - and I'd want to raise this early.

Some open questions:

- what about inherited methods?  Do we still write tests if they're inherited from `object`?
- how do we handle methods accepting other types, e.g. would we even write a test for `"a" * 3 == 3 * "a"`?
- how often do people actually write classes with these semantics, anyway?  e.g. array-oriented libraries usually give them element-wise rather than object-level semantics, and the Ghostwriter wouldn't handle that.
- `nan` breaks all of these properties.  Do we write failing tests, or (try to) add special logic for `nan`?  If so, how?

**Comment by Zac-HD** [comment]
🎉 Check out https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/ghostwriter.py, especially `_make_binop_body()` as the closest analogue of what you're trying.  The basic idea is that it's all string formatting, all the way down 😜 

Otherwise, just get an MVP up as soon as you have even non-working code.  I'm on a roadtrip for the next few weeks and only occasionally in cell range, but if you post a prototype and ask questions I (or another maintainer) will help when we can.

**Comment by Zac-HD** [comment]
Closing this as inactive: because the feature is more-or-less out of scope, I'd be happy to consider a PR but would rather not leave the issue open long-term.
