### ISSUE TITLE
Do not stop a test after it found an error

### ISSUE THREAD

**Issue by DavidFarago** [HypothesisWorks/hypothesis#3020]
I would like to configure a test such that it does not stop after finding an error, for instance with a flag `fail_continues` or an integer parameter `maxfail`. 

That would enable finding errors beyond the trivial ones, without having to fix the trivial ones first. Furthermore, getting an overview of the failures of your system is helpful for a quality rating and for estimating how many iterations of fix -> rerun Hypothesis tests will be required to reach a certain quality level.

@Stranger6667 told me that changing the Hypothesis' internal DB behavior would enable more fuzzing-like workflows and might be revisited later. Maybe this issue helps as reminder or prioritization...

**Comment by Zalathar** [comment]
(I've edited the question to say “test” instead of ”strategy” because I think this is what you actually mean; in Hypothesis we use *strategy* to refer to things like `integers()` that describe what values to generate.)

**Comment by Zalathar** [comment]
We already do some amount of this automatically (#1781), but only within some conservative limits, and we currently don't have any API to opt into a more thorough attempt to find multiple bugs (e.g. using the entire `max_examples` budget).

This is a pretty reasonable request; I think the biggest question is figuring out precisely what the API should look like. We want something that's easy to discover/understand/use, and avoids accidental misuse.

**Comment by Zac-HD** [comment]
I think adding a new allowed value for the [`report_multiple_bugs` setting](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.report_multiple_bugs) would work as an API; and with `typing.Literal` I'm inclined to make it a magic string instead of adding a new enum (and deprecating booleans, etc). Docs plus editor popups should handle discovery; so the remaining questions are "what should we name it?" and "who implementats it?" 🙂

**Comment by Zac-HD** [comment]
I think this is [best addressed by using an external fuzzer](https://hypothesis.readthedocs.io/en/latest/details.html#use-with-external-fuzzers) to drive your tests.  (that's why I built HypoFuzz as a separate tool!)

- The fairly tight limits on multiple-bug discovery are about as loose as I thought we could go without hurting the user experience, and I still wonder if that was a mistake to support at all.
- "Fix the bug you found" is a core part of the Hypothesis workflow; in normal operation *your tests should not fail*.
- [The cost of finding additional bugs scales exponentially](https://mboehme.github.io/paper/FSE20.EmpiricalLaw.pdf), so using a coverage-guided fuzzer (with polynomially-better scaling behaviour) is actually very important in practice
