### ISSUE TITLE
Question: how to create strategy from method signature?

### ISSUE THREAD

**Issue by invokermain** [HypothesisWorks/hypothesis#3023]
Is there a saner way of creating a given mapping satisfying a method's signature?

For example I believe this works:

```python
@given(
    params=st.fixed_dictionaries(
        {k: st.from_type(v) for k, v in some_method.__annotations__.items()},
    ),
)
def test_some_method(params):
    connect_data_type(**params)
    
    if params["some_key"]:
        ... assert some behaviour etc
```

Is this even a good idea?

Apologies if this is in the docs somewhere I have been trying to find something like this, potentially st.functions() satisfies this?

If there is a good way of doing this, is it possible to overwrite particular keys as it is with `st.builds` and kwargs?

**Comment by Zac-HD** [comment]
You should [use `typing.get_type_hints()` instead of accessing `__annotations__`](https://docs.python.org/3/library/typing.html#typing.get_type_hints), but this otherwise looks reasonable to me.  For customised override logic, you'd probably need to write something by hand.

(If you don't mind using undocumented internals, you could try `builds(some_method).kwargs` (or `.wrapped_strategy.kwargs` - but beware, that may raise definition-time errors / break at any time / behave weirdly in other ways.  Information only, not endorsement.)

**Comment by invokermain** [comment]
Nice, I never knew that typing utility existed, seems very useful, thanks for the input 👍

**Comment by invokermain** [comment]
For completeness on the question here is the solution wrapped in a method:

```python
def from_method_signature(method, **kwargs) -> SearchStrategy:
    return st.fixed_dictionaries(
        {
            **{
                k: st.from_type(v)
                for k, v in typing.get_type_hints(method).items()
                if k != "return"
            },
            **kwargs,
        }
    )
```
