### ISSUE TITLE
Questions on state machine behaviour

### ISSUE THREAD

**Issue by aplainzetakind** [HypothesisWorks/hypothesis#3079]
I'm trying to use the rule based state machine to test a Django database sync function. Stripped down, what I'm doing looks like this:

```python
class SyncMachine(RuleBasedStateMachine):
    @rule(strat())
    def add_to_current_chunk(self):
        # Draw from strat and add to the list self.current_chunk

    @rule()
    def sync_chunk():
        # Write the items in self.current_chunk to the database and clear it


# I'm mixing the Django TestCase in for it to do its test database magic.
class ActualTestCase(SyncMachine.TestCase, hypothesis.extra.django.TestCase):
    settings = Settings(max_examples=MAX_EXAMPLES,
                        stateful_step_count=STEP_COUNT)
```
My first and major problem is that the settings I specify as above seem to be completely ignored. I'm stumped on that.

Secondly, I'm using some instance and class attributes to track what is being done in each step and logging them. What seems to happen is that while some runs do go the distance, a lot (about a quarter) of the test runs simply terminate without executing either rule. Many of them take a handful of steps and are done. Is this intended behaviour? (I should note that both of my rules have constraints as that may be relevant, but they are mutually exclusive so the rules can't be simultaneously blocked).

Also, while the default `max_examples` is 100, the test case seems to run about 260 examples (varies). Do some of the runs not count for some reason?

Finally, many test runs are done without calling the `sync_chunk` rule even once. It would be nice to have a terminating counterpart to `initialize`. I'm guessing it's inappropriate to put testing logic in `teardown`?

I realize this is sort of multiple questions in one issue, but I figured they are a sufficiently related cluster so that this is preferable to spamming the issue board.

Thanks.

**Comment by Zac-HD** [comment]
Hi!  Quick answers:

- Try using `@settings()` as a decorator on the `SyncMachine` class.  This is a little weird, but we set a bunch of internal attributes and getting the scoping right later would be really tricky.
- Yep, sometimes stopping early is intended.  It has to be possible *sometimes* or we'd never shrink; this is much more common than usual due to the interaction of [our "swarm testing" heuristic](https://blog.regehr.org/archives/591) and having relatively few rules.
- Runs won't count if there's no available actions, which *can* happen if swarm testing has disabled some rules.
- Putting some final testing logic in `teardown` is fine!  Just be careful that you still run any cleanup logic if those final asserts fail 😉 
  (`try`/`finally` is good for that kind of thing)

Good luck, and I hope you find and fix any bugs quickly 😁
