### ISSUE TITLE
`from_type` raises TypeError for `Union` of builtin generic types

### ISSUE THREAD

**Issue by SDesch** [HypothesisWorks/hypothesis#3080]
On the current version of hypothesis (6.17.4) on python 3.9.2 

```python
st.from_type(Union[list[str], str]).example()
```

raises `TypeError("issubclass() arg 1 must be a class")` because `list[int]` is an instance of `types.GenericAlias` and not an instance of `type`.

**Comment by SDesch** [comment]
I think [this guard against types that are not really types](https://github.com/HypothesisWorks/hypothesis/blob/c4fb7c28ba7af68c7f78cb01c4642cdb51d826cc/hypothesis-python/src/hypothesis/strategies/_internal/types.py#L84) 

should be 

```python
if isinstance(t, types.GenericAlias):
    ....
```

Bonus fact: if this need to guard against `Union` too the check should also include `typing._UnionGenericAlias` as that is not a subclass of `GenericAlias` for some reason.

**Comment by Zac-HD** [comment]
Huh, yeah - thanks for the report!  Looks like we missed/under-tested the equivalent of #2979 for Python 3.9 ([PEP 585](https://www.python.org/dev/peps/pep-0585/)).

**Comment by Zac-HD** [comment]
OK, that *specific* check can just use a `try`/`except TypeError`.

The underlying problem is that we have never really tested Hypothesis with [the new-in-3.9 `types.GenericAlias` type](https://docs.python.org/3/library/stdtypes.html#types-genericalias), which I expect to see a lot more of over the next few years (e.g. `list[int]` is a lot more attractive than constantly importing stuff from the `typing` module).  I expect that we'll need to update a few things to check "is this type generic" in a more, um, *generic* way; at least accessing `__origin__` and `__args__` seems to work the same way.
