### ISSUE TITLE
Calling st.register_type_strategy imports numpy

### ISSUE THREAD

**Issue by rsokl** [HypothesisWorks/hypothesis#3154]
This is the "offending" block:

https://github.com/HypothesisWorks/hypothesis/blob/65b4b2102b94463af95a94a9994e77cfaf12f275/hypothesis-python/src/hypothesis/strategies/_internal/types.py#L493-L501

This test

https://github.com/HypothesisWorks/hypothesis/blob/65b4b2102b94463af95a94a9994e77cfaf12f275/hypothesis-python/tests/numpy/test_import.py#L16-L29

can be made to fail by modifying the src-string to be:

```
SHOULD_NOT_IMPORT_NUMPY = """
import sys
from hypothesis import given, strategies as st

@given(st.integers() | st.floats() | st.sampled_from(["a", "b"]) | st.just(st.register_type_strategy(int, st.integers())))
def test_no_numpy_import(x):
    assert "numpy" not in sys.modules
"""
```

This was causing a headache for me when figuring out why numpy was being imported the instant I ran pytest... this was because I happened to have installed numpy + hypothesis + pydantic (which uses `st.register_type_strategy` via our entrypoint).

This could be a big headache for testers over at, say, PyTorch, who want to test that they don't cause numpy to be imported.

**Comment by Zac-HD** [comment]
If I expected this to require a nasty patch - i.e. worse than our numpy special case in `register_random` - I wouldn't consider it worth fixing.

That's because once we make our pytest plugin lazily load Hypothesis (#3140), this will only trigger if you deliberately `import hypothesis` *and* somehow call `st.register_type_strategy()` *in the test that Numpy is not imported*, which usually happens in a fresh process.

Other libraries will never get this special treatment, but Numpy is already exceptional in our code and the ecosystem.
