### ISSUE TITLE
Add `allow_subnormal` kwarg to `floats()`

### ISSUE THREAD

**Issue by honno** [HypothesisWorks/hypothesis#3155]
Currently `floats()` generates subnormal floats, which would not be desired when testing "flush-to-zero" libraries (the one concrete use case being CuPy in data-apis/array-api-tests#42). The subnormals generated could be filtered out, but it would be nice if there was first-party support from Hypothesis, especially as how tricky such filtering could be for an end user.

I can take a look at doing this myself tomorrow, but mind I've never touched `floats()` before heh. I guess I'd need to figure out how to calculate the normal-subnormal boundary with width via the IEEE 754 standard.

**Comment by Zac-HD** [comment]
This will be, effectively, a filter in [`FloatStrategy.permitted()`](https://github.com/HypothesisWorks/hypothesis/blob/65b4b2102b94463af95a94a9994e77cfaf12f275/hypothesis-python/src/hypothesis/strategies/_internal/numbers.py#L203-L215) for unbounded floats - for bounded floats since they're strictly positive at this low level you can adjust the lower bound.

To get the bounds, see [`sys.float_info.min`](https://docs.python.org/3/library/sys.html#sys.float_info) and the note.  For 32bit and 16bit floats I think you'll just need to calculate the bounds as module-constants.

**Comment by Zac-HD** [comment]
We might also add a more specific error message for this case, e.g.

```python
if (
    np.issubdtype(self.dtype, np.floating)
    and result[idx] == 0
    and 0 < abs(val) < np.finfo(self.dtype).tiny
):
    raise InvalidArgument(
        f"Generated subnormal float {val}, but adding it to the array "
        f"resulted in {result[idx]!r}, probably as a result of IEEE-754-"
        "violating compiler options like -ffast-math.  Consider passing "
        "allow_subnormal=False."
    )
```
