### ISSUE TITLE
Support Petri nets in Hypothesis

### ISSUE THREAD

**Issue by ligurio** [HypothesisWorks/hypothesis#3202]
Hypothesis supports FSM as a part of [stateful testing](https://hypothesis.readthedocs.io/en/latest/stateful.html).
However, in some cases, Petri nets are more convenient for modelling a System Under Test.
Is it possible to support Petri nets in Hypothesis?

### Links:

- Python library [SNAKES: A flexible high-level Petri nets library](https://hal.archives-ouvertes.fr/hal-01186407/document)
- [What's the difference of Petri Nets and Finite State Machines?](https://stackoverflow.com/questions/53980748/whats-the-difference-of-petri-nets-and-finite-state-machines)

**Comment by Zac-HD** [comment]
We absolutely can support Petri nets - in fact, I think that our current `RuleBasedStateMachine` API can express them just as easily as FSMs (Finite State Machines).  To be more specific, that's because every `RuleBasedStateMachine` is defined in terms of the transition rules, which may optionally have preconditions to fire, and may add to / draw from / consume from "bundles" of variables; there's no requirement that the machine be in one of a finite set of enumerated states.  I'm pretty sure that this is sufficient to express arbitrary Petri nets, though the user experience might be improved by a more specialised interface.

Can you say more about the problem that prompted this, and maybe sketch some code using your dream API for a solution?

I suspect that e.g. integrating with SNAKES to automatically derive tests from a net definition would best be prototyped downstream (~~`hypothesnakes`~~ `hypothesis-snakes`?), but I'd be happy to discuss and help with design and review 😄

**Comment by ligurio** [comment]
@Zac-HD Thanks for quick response!

I definitely forgot about the ability to add a new functionality via extension. I'll try to sketch or make a PoC.

> I suspect that e.g. integrating with SNAKES to automatically derive tests from a net definition would best be prototyped downstream (hypothesnakes hypothesis-snakes?), but I'd be happy to discuss and help with design and review smile

To be honest, this issue is not about solving my real problems, but about yet another idea to make Hypothesis better :)

**Comment by ligurio** [comment]
Perhaps the issue should be closed if Hypothesis authors don't have a spare time to implement it.
I will come in case of questions if I'll face them.

**Comment by Zac-HD** [comment]
It's not so much that we don't have the time, as that Hypothesis stateful testing already supports Petri nets! (and FSMs as a special case of those, of course) 

I don't think we can improve it much further without a concrete usecase, so I'll close this for now.
