### ISSUE TITLE
Documentation for running `whole-repo-tests` locally

### ISSUE THREAD

**Issue by gjoseph92** [HypothesisWorks/hypothesis#3213]
AFAICT, the [testing guide](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/testing-hypothesis.rst) does not cover running the `whole-repo-tests` locally. Naively running `python -m pytest whole-repo-tests/test_type_hints.py` after following the [test virtualenv instructions](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/testing-hypothesis.rst#setting-up-a-virtualenv-to-run-tests-in) gives an error about `hypothesistooling` not being installed. `pip install -e tooling` solves that, but then I get:
```
==================================================================================== ERRORS ====================================================================================
_____________________________________________________________ ERROR collecting whole-repo-tests/test_type_hints.py _____________________________________________________________
Traceback (most recent call last):
  File "/Users/gabe/dev/hypothesis/whole-repo-tests/test_type_hints.py", line 16, in <module>
    from hypothesistooling.scripts import pip_tool, tool_path
  File "/Users/gabe/dev/hypothesis/tooling/src/hypothesistooling/scripts.py", line 57, in <module>
    __calc_script_variables()
  File "/Users/gabe/dev/hypothesis/tooling/src/hypothesistooling/scripts.py", line 54, in __calc_script_variables
    globals()[name] = os.environ[name]
  File "/Users/gabe/.pyenv/versions/3.9.1/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'BUILD_RUNTIMES'
```

It seems these tests expect to be running in a CI-like environment? Documentation on how to run these sorts of tests locally would be helpful, since triggering them through CI is a pretty slow cycle.

**Comment by Zac-HD** [comment]
Ooh, yeah - turns out [our testing guide](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/testing-hypothesis.rst) doesn't explain this, only https://github.com/HypothesisWorks/hypothesis/blob/master/CONTRIBUTING.rst#the-build

Let's copy across the relevant parts, and show the list-all-commands command too (which I don't recall right now :sweat_smile:)

**Comment by gjoseph92** [comment]
@Zac-HD I tried `./build.sh` as well (`build.sh tasks` lists all the commands), but it wasn't that clear what they meant (does `check` mean "run tests"?).
```
    audit-conjecture-rust
    audit-rust-in-ruby
    bundle
    check-conjecture-coverage
    check-conjecture-rust-format
    check-coverage
    check-django22
    check-django32
    check-django40
    check-examples3
    check-format
    check-installed
    check-nose
    check-pandas10
    check-pandas11
    check-pandas12
    check-pandas13
    check-pandas25
    check-py310
    check-py310-pyjion
    check-py311
    check-py37
    check-py38
    check-py39
    check-pypy37
    check-pypy38
    check-pytest46
    check-quality
    check-requirements
    check-ruby-tests
    check-rust-in-ruby-format
    check-rust-tests
    check-whole-repo-tests
    compile-requirements
    deploy
    documentation
    format
    format-conjecture-rust-code
    format-rust-in-ruby
    lint
    lint-conjecture-rust
    lint-ruby
    lint-rust-in-ruby
    python
    shell
    tasks
    upgrade-requirements
```

Anyway, I tried `build.sh check-whole-repo-tests`, but it's consistently failing with
```
+ /var/folders/rs/wdnmv5lj02x7sh19rg3nyfyr0000gn/T//.hypothesis-runtimes/virtualenvs//build-facdde0835/bin/python -m hypothesistooling check-whole-repo-tests
tar: Option --wildcards is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   668  100   668    0     0    512      0  0:00:01  0:00:01 --:--:--  6301
  0 17.1M    0 16434    0     0   9953      0  0:30:11  0:00:01  0:30:10  9953
curl: (23) Failed writing body (0 != 1362)
```
Being unsure whether that command was even what I wanted, I didn't look into it more.

**Comment by Zac-HD** [comment]
Yep, that's the command you want.

Looks like our build tooling doesn't install `stack` correctly on OSX, which is plausible since we run all the misc CI stuff on Linux workers and just test on OSX in CI.  See [this SO post](https://github.com/HypothesisWorks/hypothesis/blob/09e5035edbb68fafb1012c0e910da31d1bc3b370/tooling/src/hypothesistooling/installers.py#L60-L65 and https://stackoverflow.com/questions/40811165/extracting-specific-files-with-file-extension-from-a-tar-xz-archive-using-macos); we'll probably just need a branch which omits `--wildcards` and uses the OSX link.  Or just skip this component and the relevant tests on OSX, that's probably easier.
