### ISSUE TITLE
Is hypothesis data determinative?

### ISSUE THREAD

**Issue by mas-4** [HypothesisWorks/hypothesis#3258]
Hi, I have a pretty simple question I can't figure out the answer to from the docs.

Is the data hypothesis feeds to a test determinative? I.e., does it change between test runs or will it always be the same?

**Comment by honno** [comment]
Nope. Example generation (i.e. the data being fed to tests) depends on RNG, which in typical environments will almost always will not generate the same examples/data each time. The examples/data might look pretty similar between runs though, due to how strategies (i.e. data generators) use heuristics to figure out what to generate.

Note you can _somewhat_ reproduce generation with [`@seed()`](https://hypothesis.readthedocs.io/en/latest/reproducing.html#reproducing-a-test-run-with-seed). It can sometimes be useful when developing and debugging, but something most folks don't need.
