### ISSUE TITLE
Lark plugin - Fund maintenance?

### ISSUE THREAD

**Issue by erezsh** [HypothesisWorks/hypothesis#3259]
Hi,

Reading https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis-lark, I noticed

> We may also be quite aggressive in bumping the minimum version of Lark, unless someone volunteers to either fund or do the maintenance.

Which made me wonder, is there a way to fund work for this specific plugin, to keep it up to date and ensure it's working well? And if so, how much of a donation would be appropriate for that?

I would of course be happy to help whoever ends up doing the maintenance, by answering questions and providing directions, if necessary.

**Comment by Zac-HD** [comment]
👋 Hi Erez, and thanks for Lark!

Since we wrote that we haven't actually needed to drop compatibility with any versions, and with Lark 1.0 out (congrats!) I don't expect to do so unless supporting 0.x made developing new features substantially more difficult.

Funded development would presumably aim at [our open issues](https://github.com/HypothesisWorks/hypothesis/issues?q=is%3Aissue+is%3Aopen+label%3Alark), roughly taking `hypothesis[lark]` from "useful beta" to "mature and polished".  This is a case for a support contract rather than donation; unfortunately my work leaves me unavailable for this though like you I'm always happy to review code, answer questions, and generally assist people contributing to Hypothesis.

**Comment by erezsh** [comment]
> unfortunately my work leaves me unavailable for this

I understand. Actually, I don't have a need for support at the moment. I'm just looking for opportunities to advance and improve Lark, and luckily I have a tiny budget to disperse for that purpose. If you find yourself with free time in future, and feel like tackling those issues that you linked, let me know.

Thanks for everything you've done so far!

**Comment by Zac-HD** [comment]
Closing because this isn't actionable at the moment, but thanks again for starting the conversation 🥰
