### ISSUE TITLE
Option to limit cycles in stateful testing.

### ISSUE THREAD

**Issue by adriangb** [HypothesisWorks/hypothesis#3305]
First off, I am quite new to property base testing and I think I'm only using a small percentage of Hypothesis, so apologies if this is just lack of knowledge on my end.

Would it be possible to add some way to limit cycles in stateful testing? For example, saying "only cycle through states 2 times" to avoid: `A -> B -> A -> B -> A -> B` to `A -> B -> A -> B` or "no cycles" to cut it off at `A -> B -> A` or something like this.

As far as I understand it there are settings to limit the max examples (`max_examples `) and number of state transitions (`stateful_step_count`) but no option to avoid / limit cycles.

**Comment by Zac-HD** [comment]
Hi Adrian - this is harder than it sounds, because Hypothesis state machines are defined in terms of *transition rules* rather than *states*, and so the cycles you illustrate might actually be invoking different behaviour on each iteration.  More generally, we can't be sure what side effects might be getting tested on each apparent cycle, so this might weaken our tests.

My overall advice in this situation is basically to just relax - Hypothesis does have *internal* detection of redundancy (though it's an under-approximation, for safety) - and turn up the `max_examples` if you're concerned about missing bugs.  It would be possible to implement such a cycle-preventer yourself using `@precondition`, but be careful not to rule out too much.

**Comment by adriangb** [comment]
Gotcha. Yeah I agree it's a balance: ideally you would test everything, but ultimately you can't, so you have to put some sort of limitation on what gets tested. I just thought that this might be a nice knob to tune.

Could you point to me to an example of using `@precondition` to do something like this?

**Comment by Zac-HD** [comment]
> Could you point to me to an example of using `@precondition` to do something like this?

I actually don't know of any, sorry - to sketch out my thoughts, you could have each rule append "invoked rule.__name__" to a list on the class, and then a precondition on each rule which can check if invoking this rule after that history would form a cycle.  It's not going to be pretty without building some pretty serious machinery out of decorators, but if I had to this is how I'd do it.

**Comment by adriangb** [comment]
Thank you. If I ever get around to building it out I'll report back 😅!
