### ISSUE TITLE
HealthCheck sensitivity is not appropriate in all contexts

### ISSUE THREAD

**Issue by epgui** [HypothesisWorks/hypothesis#3367]
When generating relatively large json objects (or even arrays of such objects), one will frequently run into either a `too_slow` or a `data_too_large` HealthCheck failure.

While it is possible to disable these checks, doing so foregoes any benefit that the HealthCheck is supposed to bring.

In many situations, it would be preferable to have an option to tweak the sensitivity level of health checks. Maybe I know roughly how much data I want to generate, and I am okay with CI taking a few extra seconds to run my tests.

**Comment by Zac-HD** [comment]
The goal of the HealthCheck system is just to ensure that you know if you're hitting these unusually large or slow cases - if that's intentional (which in your case it is), disabling them is perfectly fine.

We should probably reframe `HealthCheck.too_slow` in terms of the `deadline` setting, though 🤔
