### ISSUE TITLE
Ignoring the first unreliable test timing error

### ISSUE THREAD

**Issue by gmacon** [HypothesisWorks/hypothesis#3369]
We've been experiencing occasional failures due to tests being slow on the first attempt. While we were unable to definitively identify the cause of the flakiness, our best guess at the moment is that, in our containerized CI, the first access to the `/tmp` directory can be arbitrarily delayed. (The test in question is round-tripping data through serialization code.) Over time, we've raised the deadline on that test up to 20 s (i.e. `deadline=20000`), until I finally gave up and made the code work with arbitrary file-like objects (instead of needing a real file) and we're now using `io.BytesIO`.

This triggered a discussion about whether Hypothesis could be improved to avoid this particular annoyance. While looking to see if there was an existing issue, I discovered that @DRMacIver had said in https://github.com/HypothesisWorks/hypothesis/issues/2108#issuecomment-537070253:

> In general I wonder if we should modify the deadline code to be a little more forgiving of flakiness to cope with this sort of lazy loading of global resources in general - say give the code some small bounded number of deadline-exceeding test runs which it will rerun to see if they're still deadline exceeding and just shrug and ignore them if they're not.

I'm curious if any further thought or effort had been put into this. I didn't find anything looking through issues here. I think the correct "bounded number" is "one per test function", but we might want to make that configurable.

I took a quick look at the code, and the "obvious" thing I thought to try was to change this condition: https://github.com/HypothesisWorks/hypothesis/blob/a11ec6f2ba4c1d08df6e355730d2a25d317492db/hypothesis-python/src/hypothesis/core.py#L668-L671 to not report failure on the first non-reproduction, but I don't know how badly that will break everything else. Another possibility is to simply declare that, instead of one flaky-slow test for free, you get one slow test for free and not raise `DeadlineExceeded` on the first slow test.

**Comment by Zac-HD** [comment]
I'm kind of torn here.  It seems that any option is going to be a bad experience for *someone*, so we're looking at tradeoffs:

- On one hand, a configuration option for this is *right out*, and I'm reluctant to complicate the semantics of `deadline` when it currently has such a clear interpretation.  Simply documenting more complicated behaviour for new users to learn has a cost to UX, even when it's not configurable.
- On the other, "we don't raise `DeadlineExceeded` for the first offence if it's fast on replay" is still pretty simple and does handle a pain point around slow one-time warmup (which is a pretty common pattern).
- On the gripping hand, this only handles *one-time* warmup, with a side effect of making it more difficult to understand what's going on in more complicated cases.  Similar to the first point from a different angle, I guess.

While I sympathasize with your experience (and really value the issue - thanks!), it seems likely to me that the best overall solution for such issues is going to be downstream, with something project-specific like your use of `BytesIO` or a `touch /tmp` in a setup script somewhere, rather than changing Hypothesis itself 😥

**Comment by Zac-HD** [comment]
Closing this because I think that the more complicated logic would on net cause more confusion and wasted time than it saves 😞
