### ISSUE TITLE
[Feature] Ignore pytest skip/xfail exceptions in Flaky check

### ISSUE THREAD

**Issue by brandon-leapyear** [HypothesisWorks/hypothesis#3416]
We have some tests that are known to be flaky (there's some race condition in the backend we're querying), which we catch and throw `pytest.xfail()` when it occurs. But when this happens, hypothesis raises
```
hypothesis.errors.Flaky: Hypothesis test_foo(...) produces unreliable results: Falsified on the first call but did not on a subsequent one
```
It would be nice if, when hypothesis runs the same input and gets the result `pass / xfail` or `pass / skip`, to consider it successful.

Alternatively, it would be nice to be able to manually disable the flakiness check for a test.

**Comment by Zac-HD** [comment]
Can't disable the flakiness check, because "reproduce the same error (or non-error) when passed the same arguments" is a core part of how Hypothesis works.  In this case, I'd suggest doing:

```python
@given(...)
def test(...):
    with contextlib.suppress(pytest.XFailed):
        "Your test code here"
```

or maybe setting up some automatic retries so that it's not flaky.  In the worst case, we *do* recognize "skip" exceptions as a signal to end the test immediately, and pytest/unittest will treat that as a skip rather than failure.

**Comment by brandonchinn178** [comment]
> we _do_ recognize "skip" exceptions

can similar logic be done for xfail exceptions?

**Comment by Zac-HD** [comment]
Harder than it sounds: an "xfail exception" is a concept unique to Pytest; and once there are *two* kinds of special exceptions things get really complicated - even before handling `ExceptionGroup`.  In any case you can implement this yourself within the test body, either `return`ing on xfail, converting it to a skip exception, or whatever else makes sense for you.

(or, in an ideal world, either fix or migrate away from the flaky backend, which is the core of the problem)
