### ISSUE TITLE
--hypothesis-show-statistics

### ISSUE THREAD

**Issue by Aarsh2001** [HypothesisWorks/hypothesis#3443]
For some functions it shows `stopped because max examples` and for others it shows `stopped because nothing left to do` and doesn't even generate max number of examples. Is there any explanation for this behaviour.

**Comment by Zac-HD** [comment]
The `max_examples` setting also counts the `reuse` phase where we replay examples from the database, and generation might stop even earlier if we can tell we've tried every possible example - e.g. `@given(st.booleans())` will never generate more than two examples (`False` and `True`) before stopping, because what would be the point?

**Comment by Aarsh2001** [comment]
can we wrap the given decorator with some other decorator, or would that lead to breaking changes?

**Comment by Zac-HD** [comment]
Yes, almost all decorators should work, eg you can use both pytest parameterize and given on the same test.
