### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class when registering custom strategies for NewTypes

### ISSUE THREAD

**Issue by stevegerrits** [HypothesisWorks/hypothesis#3447]
When registering custom strategies for NewType object's I stumbled across the following:

`TypeError: issubclass() arg 1 must be a class`

I used the example from following existing ticket:  https://github.com/HypothesisWorks/hypothesis/issues/1911

```
    strategy = st.characters(whitelist_categories='L')
    st.register_type_strategy(MyNewType, strategy)
    example = st.from_type(MyNewType).example()
    assert isinstance(example, str) and len(example) <= 1
```

I have `hypothesis 6.54.4` installed and use `Python 3.8`
Downgrading to `hypothesis 6.39.3` resolves the bug

**Comment by Zac-HD** [comment]
I've been unable to reproduce this - on my machine at least, it's working on both new and old versions of Python.  Please post a [complete minimal reproducing example](https://stackoverflow.com/help/minimal-reproducible-example), *and* the full traceback that you see so that I can check whether I'm getting the same error (or maybe work out what's going wrong for you).

**Comment by Zac-HD** [comment]
@stevegerrits - can you please post the code that you ran, and the traceback that you saw?  Without those or the ability to reproduce locally, there's nothing I can do 😢

**Comment by stevegerrits** [comment]
@Zac-HD Sure, sorry for the late reply. Will post it later this week

**Comment by Zac-HD** [comment]
Ping @stevegerrits?

**Comment by Zac-HD** [comment]
Closing this as inactive / can't reproduce 😢 

If anyone reading this *can* repro and tell me how, I'd be very happy to reopen and fix it!
