### ISSUE TITLE
Feature request for stateful testing: pass generated values to preconditions

### ISSUE THREAD

**Issue by chenlijun99** [HypothesisWorks/hypothesis#3448]
Hi. I'm trying to use the powerful stateful testing method of Hypothesis, but I would like to filter some generated data in `@precondition`, but it doesn't seem to be possible now.

What I would like is something like:

```py
@rule(x=st.integers())
@precondition(lambda self, x: x not in self.lst)
def apply_new_integer(self, x):
    ...
```

Did I miss something in the documentation or is it not supported by Hypothesis?

Thanks!

**Comment by Zac-HD** [comment]
This isn't supported directly in the `@precondition()` decorator, but there are two idiomatic ways to do this:

- Instead of using `@precondition()`, write `assume(x not in self.lst)` as the first line of the method.  This is very easy, but might be inefficient as it forces Hypothesis to throw out the whole stateful sequence and retry if it fails.
- Ensure that `self.lst` is available in class scope, and use `x=st.integers().filter(lambda x: x not in lst)`.  This is much more efficient because Hypothesis can retry *without* restarting the whole stateful test, but might require some further modifications to e.g. call `self.lst.clear()` at setup or teardown.

I'd recommend the latter.

**Comment by chenlijun99** [comment]
I was doing it the first way, but I also think that the second is better. Thanks for the suggestions!
