### ISSUE TITLE
strategy for pydantic model with validator

### ISSUE THREAD

**Issue by sziem** [HypothesisWorks/hypothesis#3457]
I have a pydantic model with a root validator and I am trying to get a hypothesis strategy for it.  However, I frequently get a ValidationError.  Is there a way I can make hypothesis understand the validator, so that I don't have to write a custom strategy for my model?

I don't have a concrete idea on how it would look, but it would be a great feature to be able to specify custom restrictions/assumptions on individual pydantic fields.

This is a basic example of what I am trying to achieve:
```python
import hypothesis
import pydantic

class MyModel(pydantic.BaseModel):
    a: int = 0
    b: int = 1
    
    @pydantic.root_validator
    def a_smaller_b(cls, values: dict) -> dict:
        if values["a"] >= values["b"]:
            raise ValueError("a<b")
        return values

st_my_model = hypothesis.strategies.from_type(MyModel)
for i in range(10):
    print(st_my_model.example())  # frequently produces Validation Error
```

**Comment by Zac-HD** [comment]
> Is there a way I can make hypothesis understand the validator, so that I don't have to write a custom strategy for my model?

Maybe - the problem is that if you're rejecting more than about 10% of all examples, the tests are going to be both considerably slower and qualitatively less diverse, to the point that Hypothesis will eventually refuse to keep trying.  If it's rare:

```python
def from_type_without_validation_error(model):
    strategy = st.from_type(model)
    @st.composite
    def inner(draw):
        try:
            return draw(strategy)
        except ValidationError:
            assume(False)
    inner.__name__ = f"from_{model.__name__}"
    return inner()

st_my_model = from_type_without_validation_error(MyModel)
```

Otherwise, you'll need to write a custom strategy which ensures that the values are always valid:

```python
# This can be a little fiddly for complicated models, but it's worth it!
st_my_model = st.builds(
    lambda a, b_offset: MyModel(a, a+b_offset),
    a=st.integers(),
    b_offset=st.integers(min_value=1),
)

# Fortunately, you only need to do that once:
st.register_type_strategy(MyModel, st_my_model)
assert st_my_model == st.from_type(MyModel)  # OK
```

The latter case is easier than it might sound, because if your models have other models as attributes, you can build them up iteratively.  Another nice trick is to give your models a constructor which takes the place of the lambda in the above example:

```python
class MyModel(pydantic.BaseModel):
    ...  # all the other stuff

    @classmethod
    def from_random_args(a: int, b_offset: int):
        return cls(a, a+abs(b))

st_my_model = st.builds(MyModel.from_random_args)
# If we hadn't added the `abs(b)` to the method, we could instead pass `b=st.integers(min_value=0)` to `st.builds()`
```
