### ISSUE TITLE
Type annotation of fixed_dictionaries expects same type in all args

### ISSUE THREAD

**Issue by jl-wynen** [HypothesisWorks/hypothesis#3467]
The type annotations for `fixed_dictionaries` require that the arguments `mapping` and `optional` both take strategies which produce objects of the same type. But the strategy works also for mixed types. For example the following works:
```.py
from hypothesis import strategies as st
st.fixed_dictionaries({'a': st.booleans()},
                      optional={'b': st.integers()})
```
but produces a type error in PyCharm for `optional`:

> Expected type 'dict[str, SearchStrategy[bool]] | None' (matched generic type 'dict[T, SearchStrategy[Ex]] | None'), got 'dict[str, SearchStrategy[int]]' instead

I cannot reproduce this with mypy and did not try other type checkers.

This could be fixed, e.g., by changing the function definition to
```.py
@defines_strategy()
def fixed_dictionaries(
    mapping: Dict[T, SearchStrategy],
    *,
    optional: Optional[Dict[T, SearchStrategy]] = None,
) -> SearchStrategy[Dict[T]]:
```

**Comment by Zac-HD** [comment]
I think we'd rather use `@overload`s and `Union` rather than dropping back to `Any` - avoiding errors by erasing the element types seems worse than taking on some extra complexity to support it.

While we're there, we should make the type annotations reflect that the mappings can be of non-`dict` type (e.g. `defaultdict`), probably using `TypeVar`.

**Comment by Zac-HD** [comment]
I've looked into this, and it seems to be a limitation of PyCharm rather than anything we can fix in Hypothesis; and I'm not willing to compromise on the annotations to work around a bug in proprietary code.  Sorry we can't help more!

I also tried using a TypeVar, but they can't be subscripted at runtime so that's a no-go too.
