### ISSUE TITLE
Strategy That Depends on Outer State

### ISSUE THREAD

**Issue by fscarlato** [HypothesisWorks/hypothesis#3469]
Let'say i want to make a strategy that generates fresh users on the fly through an API REST:

```

def make_user(user):
    resp = requests.post(user)
    if resp == 201: return just(user)
    else: return nothing()

users = user_schema.make_strategy().flatmap(make_user)
    
@given(user=users)
def test(user):
    # Do something with the user

```

Hypothesis will stop with a FlakyAssumption because if the same user is generated twice, the first POST will pass with a 201, but the sequent will fail with a Conflict 409, so the generated data won't reach the test function.

To make things works, I have to add state, store the user after a 201 Response and returning that instance when the next POST wolud return a Conflict.

Am I using the framework in the right way or I can make this whole thing easier?

Maybe I can first create a buck of state, and then using strategies that drawns from that fixed state.

**Comment by honno** [comment]
So you've got a flaky scenario with relying on an external endpoint. You could just suppress this warning (see [Settings](https://hypothesis.readthedocs.io/en/latest/settings.html?highlight=settings#settings)), although I would consider if you really want a test like this, instead of say generating "user" examples locally ([`st.builds()`](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=builds#hypothesis.strategies.builds) can make this quite easy depending on what your schema looks like).

**Comment by Zac-HD** [comment]
To avoid flakiness here, you'd need to reset the state of the API between *each test case*; or alternatively you could cache results and replay them - but you'd still need to start with the same initial state each time you ran your test suite, or replaying failed examples won't work.

Creating a sequence of users up-front and sampling from that, so long as it's the same sequence every run, might be easier 🙂
