### ISSUE TITLE
max_examples in @hypothesis.settings not working

### ISSUE THREAD

**Issue by Freemanlabs** [HypothesisWorks/hypothesis#3488]
I am not entirely sure how `@hypothesis.settings(max_examples=...)` should work.
My knowledge is that it specifies the number of examples to create.

I have:

```
@given(data=st.integers(), ndim=st.integers(min_value=5, max_value=10))
@settings(max_examples=4)
def test_settings(data, ndim):
    print("DIM ", ndim)
    ...
```
I see 12 results of "DIM", sometimes it's 3 (in a deterministic way). I am not sure why since I have specified 3 to be the max number of examples.

**Comment by Zac-HD** [comment]
The `max_examples=` setting is best thought of as a goal, but we might run *fewer* examples if we find a bug early or can tell that we've exhausted the search space, and might run *more* if we discard some examples due to use of `.filter()`, `assume()`, or a few other things that can prevent the test case from completing successfully.

I think we should add something along these lines to the docs 🙂
