### ISSUE TITLE
Why it is necessary to provide strategies to `given` even if they're later ignored?

### ISSUE THREAD

**Issue by karol-bisztyga** [HypothesisWorks/hypothesis#3513]
Hey!
I noticed that `given` is necessary to use `example` even when `phases = (Phase.explicit,)` which basically means that `given` is later ignored. I have some cases when I just want to use specific examples and still consider the test as parameterized. Would it make sense to allow it?
```
@example(200)
@settings(phases=(Phase.explicit,))
def test_xxx(arg):
  print(f"- {arg}")
```
In this case, I'd have a separate decorator that would conditionally decorate the function with `given`:
```
dct = {'arg': st.integers()}
dct = {} # with this I have an error but it would be cool if it worked the same way as it does with just the line above and this very line removed

def decorate_with_given(target_func):
    func = target_func
    if not dct:
        return func
    func = given(**dct)(func)
    return func

@decorate_with_given
@example(200)
@settings(phases=(Phase.explicit,))
def test_xxx(arg):
  print(f"- {arg}")

test_xxx()
```

**Comment by honno** [comment]
Can you use the [`pytest`](https://github.com/pytest-dev/pytest/) library? (or is there a reason not to?) Specifically [`pytest.mark.parametrize`](https://docs.pytest.org/en/6.2.x/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions).

```python
@pytest.mark.parametrize(("arg",), [200, 300, 400, ...])
def test_xxx(arg):
    ...
```

Parametrization is a feature onto itself which is already covered extensively by pytest, which I'd recommend using for almost any Python project. I doubt we'd want to make `@example` more than just a way to inject examples into property-based testing.

**Comment by Zac-HD** [comment]
> Why it is necessary to provide strategies to given even if they're later ignored?

In short, because the alternatives are worse!  If we allowed this...

- we'd have to deal with 'spooky action at a distance' where changing your settings could break otherwise-working code
- we couldn't actually be confident that the test is *always* in explicit-only mode
- we'd need to make a lot of validation logic optional or duplicated, which is just asking for trouble

and ultimately if you're only ever using explicit examples you don't really need Hypothesis!

**Comment by karol-bisztyga** [comment]
Thanks for the answers!

@honno the point here is that we have some parameterized code and I wanted to make it as generic as possible using hypothesis. I wanted to avoid adding some extra code and writing separate functions for different cases. The example I gave you here is just a minimal repro of a problem.

> ultimately if you're only ever using explicit examples you don't really need Hypothesis!

That is a point well taken.

I'm going to figure this out, thanks again for the reasoning, cheers!

**Comment by csadorf** [comment]
> > Why it is necessary to provide strategies to given even if they're later ignored?
> 
> In short, because the alternatives are worse! If we allowed this...
> 
> * we'd have to deal with 'spooky action at a distance' where changing your settings could break otherwise-working code
> * we couldn't actually be confident that the test is _always_ in explicit-only mode
> * we'd need to make a lot of validation logic optional or duplicated, which is just asking for trouble
> 
> and ultimately if you're only ever using explicit examples you don't really need Hypothesis!

@Zac-HD In our scenario we would like to _usually_ run our tests with hypothesis and maybe a few selected examples, but then also be able to run the tests with only the examples under specific circumstances. Right now we are essentially forced to skip all hypothesis-wrapped tests which also includes the parametrized examples. Is there any alternative to duplicating these tests?

For example, instead of:
```python

@given(number=st.integers(min_value=0)
def test_positive(number):
    assert number >= 0

@pytest.mark.parametrize("number", [1, 2, 3])
@test_positive_examples(number):
    assert number >= 0
```

I would like to just write
```python
@given(number=st.integers(min_value=0)
@example(number=1)
# ...
@test_positive(number):
    assert number >= 0
```
and then execute that with something like `pytest --hypothesis-skip-given`.

Maybe there is an obvious solution to my problem in which case I am happy to adopt that instead.

**Comment by honno** [comment]
I would just have a helper function covering any complicated-enough testing logic, and then use it in both paramatrized and hypothesis-powered tests.

```python
def _test_behaviour(...):
    ...

@pytest.mark.parametrize(...)
def test_behaviour_known_examples(...):
    ...
    _test_behaviour(...)

@given(...)
def test_behaviour():
    ...
    _test_behaviour(...)
```

**Comment by csadorf** [comment]
@honno Thanks for the fast reply and suggestion!

Considering that this logic would need to be implemented for hundreds of tests, the only feasible way would be to implement some kind of custom wrapper at which point we would likely replicate a lot of the pytest and hypothesis API. So, no, I don't think that's a good alternative.

The scenario here is that under specific circumstances we simply cannot allow our tests to fail, just because hypothesis detected a new edge case. So maybe a combination of `derandomize` and consistently registering all PRNGs with `register_random()` would achieve the same thing, but I am still a bit skeptical that this would be as robust as simply skipping all arbitrary tests.

**Comment by Zac-HD** [comment]
@csadorf we have a good solution for this already:

- https://hypothesis.readthedocs.io/en/latest/settings.html#phases
- you can register a settings profile with `phases=[Phase.explicit]`, and then pass `pytest --hypothesis-profile=whatever_you_named_it` to globally enable that.

**Comment by csadorf** [comment]
@Zac-HD That's fantastic – thank you for the tip! I did not realize that one could use phases for this purpose. I will try to implement this and let you know in case I run into any issues.
