### ISSUE TITLE
Generating unique data is too slow

### ISSUE THREAD

**Issue by vnpham** [HypothesisWorks/hypothesis#3532]
Hi, I'm trying to generate a pandas dataframe that has around 100 unique rows, 30 columns of text with maximum 255 characters.  I tried the hypothesis.extra.pandas.data_frames strategy but it is not simple to generate unique rows.  Eventually, I use the list of tuples to generate the data as follow

```
import hypothesis.strategies as st
from hypothesis import given, settings, HealthCheck
from datetime import datetime

count = 0


@given(st.lists(st.tuples(*[st.text(max_size=20) for i in range(30)]),
                min_size=20, max_size=30, unique=True))
@settings(max_examples=5, suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large])
def test_this_thoroughly(x):
    global count
    count += 1
    print(f"{count}: {str(datetime.now())}: {str(x)}")
    print('-'*40)
```

Even with this much smaller sizes of both the string and the list, I still have this error

```
    @given(st.lists(st.tuples(*[st.text(max_size=20) for i in range(30)]),
>                   min_size=20, max_size=30, unique=True))
E                   hypothesis.errors.Unsatisfiable: Unable to satisfy assumptions of test_this_thoroughly

hypothesis_test01.py:9: Unsatisfiable
```

I've tested the performance of generating the data of various types (int, float) for unique and not unique rows and see that the whenever I require unique data, the performance is significantly reduced.  If the data type is text, it is even much slower, and if I increase the size of the list above 10, it would give me Unsatisfiable error.

So my question is how to best generate these type of unique text data using hypothesis?

**Comment by Zac-HD** [comment]
Hi @vnpham  - generating arrays or dataframes with unique=True is much slower because [requiring unique elements disables sparse-fill mode](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.numpy.arrays), meaning that we have to generate every element individually rather than ~sqrt(n) elements.

100x30 is also on the larger side of what Hypothesis can generate - as a testing library, we focus more on generating _valid but bug-triggering_ inputs rather than _production-like_ inputs.  What's the minimal dataframe that could possibly be valid for your test?  Think about the minimal counterexample you'd want to see if the test fails, and how few rows and columns you could possibly get away with 🙂
