### ISSUE TITLE
hypothesis.note() is not working as expected after version 6.54.0

### ISSUE THREAD

**Issue by jat9292** [HypothesisWorks/hypothesis#3597]
Hello, I am using Python 3.8, 3.9 and 3.10 on Mac OS (M1 chip) and I noticed that note() function would not print anything when Verbosity is at normal level, while for versions 6.53.0 and prior are actually showing correctly the failing shrinked counter-example as expected according to documentation.
I tried to search if a similar issue was already raised, but failed to find any.

**Comment by Zac-HD** [comment]
Please provide a reproducing example?

**Comment by jat9292** [comment]
Sure
```python
from hypothesis import given, note, strategies as st
@given(st.lists(st.integers()), st.randoms())
def test_shuffle_is_noop(ls, r):
    ls2 = list(ls)
    r.shuffle(ls2)
    note(f"Shuffle: {ls2!r}")
    assert ls == ls2

try:
    test_shuffle_is_noop()
except AssertionError:
    print("ls != ls2")
```

Gives correct output with hypothesis 6.53.0 :  
```
Falsifying example: test_shuffle_is_noop(
    r=HypothesisRandom(generated data), ls=[0, 1],
)
Shuffle: [1, 0]
ls != ls2
```

But missing the note logs with hypothesis 6.54.0 or more recent versions : 
```
ls != ls2
```

**Comment by Zac-HD** [comment]
Ah, I think your environment isn't showing PEP-678 exception notes; you probably also have a warning from the `exceptiongroup` backport library about that, and it'll work on Python 3.11 and later.

So I suggest checking for libraries that install `sys.excepthook`, such as the Pycharm debugger.

Hypothesis might be able to mitigate this by checking the value of the hook, and printing notes manually if they'd be ignored otherwise.

**Comment by Zac-HD** [comment]
I think this will be fixed by https://github.com/ipython/ipython/pull/14040 - if not, I'll need more details about your environment but the resolution is probably still to go as the _other_ project to fix the problem 😅
