### ISSUE TITLE
hypothesis creates a .hypothesis directory on import if pydantic is also installed

### ISSUE THREAD

**Issue by kerrick-js** [HypothesisWorks/hypothesis#3609]
## Summary
Hypothesis seems to create a `.hypothesis` directory when you import the package if you also have pydantic installed. I think this is not good behavior; a module should never have side effects from just importing it.

## To reproduce
```
venv=$(mktemp -u)
python3 -m virtualenv $venv
cd $venv
. $venv/bin/activate
pip install hypothesis==6.70.2 pydantic==1.10.7
python -c 'import hypothesis'
ls .hypothesis
```

## Expected behavior
No .hypothesis directory

## Actual behavior
It creates a .hypothesis directory

## System information
Rocky Linux 8
Python 3.8.13

**Comment by Zac-HD** [comment]
This is due to the plugin shipped in Pydantic, and thus not something we can fix in this repo.  I do happen to know that thw plugin is due for a rewrite for compatibility with the forthcoming pydantic 2 though.

**Comment by Zac-HD** [comment]
That would make sense, though it's unlikely to be fixed (unless you fix it) before Pydantic 2.

The problem is that Hypothesis imports https://github.com/pydantic/pydantic/blob/main/pydantic/_hypothesis_plugin.py and something in that file triggers the creation of the cache directory.  Maybe a text strategy, in which case liberal use of deferred might fix it?
