### ISSUE TITLE
Question: wrapping a Hypothesis strategy around Faker

### ISSUE THREAD

**Issue by jenstroeger** [HypothesisWorks/hypothesis#3614]
More of a question, sorry, because I’m not sure if the [Hypothesis group](https://groups.google.com/g/hypothesis-users) is still active. This question came up in [this Stackoverflow thread](https://stackoverflow.com/questions/48984145/python-hypothesis-unit-test-using-faker) and is also somewhat addressed by the [hypothesis-faker](https://github.com/dycw/hypothesis-faker) package (which, at first glance, seems unnecessarily complex).

In short: how difficult would it be to build a well-functioning strategy which samples/draws from a given [`Faker`](https://faker.readthedocs.io/en/master/fakerclass.html) object?

For example, using
```python
from faker import Faker

@st.composite
def faker(draw, attr, locale=None) -> str:
    faker = Faker(locale)
    return getattr(faker, attr)()
```
I can then use
```python
>>> cities = faker('city', 'en_US')
>>> cities.example()
'Destinyshire'
...
```
or
```python
>>> colors = faker('color_name')
>>> colors.example()
'BlanchedAlmond'
...
```
This seems a bit inefficient because every draw creates a new `Faker` object (which also messes with reproducible tests) but it works. I’m also concerned that this won’t play well with shrinking (making it [Flaky](https://github.com/HypothesisWorks/hypothesis/blob/a136cb4a5f61170439918d7404eb4acfb0a617cf/hypothesis-python/src/hypothesis/errors.py#L51-L65)), and perhaps other Hypothesis goodness.

Are there better ways to have Hypothesis collaborate with Faker? Does this combination make sense at all? (Other that @Zac-HD’s comment on the Stackoverflow post.)

**Comment by Zac-HD** [comment]
We generally recommend *against* using Faker with Hypothesis, because they're designed to do two different things:
- Faker generates *realistic* data for use in e.g. demos and load-testing
- Hypothesis generates *failure-inducing* data for use in semantic tests

so IMO it's just a mistake to use Faker for the kind of test where you could use Hypothesis.[^#]

[^#]: techniques like "fuzzing dictionaries" aside, which in Hypothesis either require low-level support from the internals, or break shrinking.  It's not that difficult to improve, just a bunch of work that nobody has volunteered to do or fund yet.
----
If you wanted to anyway... `hypothesis-faker` looks like it's fundamentally mis-designed to me, on the simple criteria of "do replay and shrinking work".  IIRC most Faker objects consist of lists of possibilities to combine, so using `st.sampled_from()` might work pretty well?  I think I looked into using `st.randoms()` at some point and found it too fiddly to be worth it, but you could check that too.

**Comment by jenstroeger** [comment]
Thank you for your opinion, @Zac-HD!

Because of the flakiness when shrinking I abandoned the approach altogether, and now use Hypothesis and Faker for what they are — different tools testing with different approaches and intentions. They complement each other well, but agreed: I wouldn’t want to mush them together.

**Comment by dycw** [comment]
Just saw this issue on my repo, as I was looking through something else!

@Zac-HD is absolutely right in that Faker source code is essentially a big list of lists (organised by domain & locale) to which `sampled_from` could be used on directly.

However, the main challenge in the proof of concept of `hypothesis-faker` was to get as much of the various domains (and only one locale) made readily available, without having to copy & paste all these lists directly and to be easily able to keep up with upstream logic. Hence why I settled on the simple caching logic.

Would be interested in reviving this and doing it more properly as I have some person need to pull in this domain specific fake-data!
