### ISSUE TITLE
Deadlines and CI environments

### ISSUE THREAD

**Issue by tjni** [HypothesisWorks/hypothesis#3713]
I have been contributing to [nixpkgs](https://github.com/NixOS/nixpkgs), which builds Python packages from source, and I have seen, from time to time, tests using hypothesis have their deadline exceeded because of CI constraints. For instance, a package might run a CPU-bound test, but the CPU is tied up by a build of something completely different (we build a lot of C/C++/Rust packages too).

Looking for a solution that lets us externally tweak the deadline to be more generous for our use case. I'm open to ideas and would be willing to work on whatever is decided.

Thank you!

**Comment by Zac-HD** [comment]
https://hypothesis.readthedocs.io/en/latest/settings.html#settings-profiles would probably be useful?

You'll need to inject a bit of Python code _somewhere_, e.g. via a `conftest.py` for pytest or the more general sitecustomize hooks, but can then disable the deadline entirely (appropriate if you're not maintaining the package!) and configure whatever other settings you like.

**Comment by tjni** [comment]
Thanks for the suggestion! That does sound like it's on the right track. Can we turn this into a feature request for an easier way to inject and overwrite profiles? Consider:

1. As the package manager, we can patch source code, but that might require inspecting the code of each package and crafting some Python code for each one. It can break if the code changes, and it is also hard to scale this knowledge and process to many contributors. It also is hard to generalize if we want to build something automated (e.g. if we detect that hypothesis is on the PYTHONPATH when running a test, always tweak the deadline).

2. We do not want a totally different profile, only substitute the parts that we care about. For those parts, we want that to apply to every profile the package itself uses. And we also do not want to lower a deadline if a package has better knowledge and raises it for some specific profile.

**Comment by Zac-HD** [comment]
For your specific use-case, the best option might be a tiny patch to your copy of Hypothesis which unconditionally sets `deadline=None` regardless of user configuration!  Again, I think that disabling deadlines entirely is appropriate for you because they're intended as development feedback for the test author / package maintainer, not downstream packaging.

Unfortunately a general mechanism seems infeasible, because packages might use it too!  

You can create new profiles which inherit all unspecified options from a specified other profile, defaulting to the current profile, which is how I imagined that you'd adjust the settings when executing code.

**Comment by tjni** [comment]
Got it. If I understand, your perspective is that you want changing the deadline to always be explicit in the test code, which means it is necessarily harder for package managers to do this in general. I'll see what we can do on our side. Thanks for the perspective and response.
