### ISSUE TITLE
Add C style integer types to integers() strategy?

### ISSUE THREAD

**Issue by jenstroeger** [HypothesisWorks/hypothesis#3754]
Hello, today I had to deal with a bunch of integer numbers that had to fit into C style types (e.g. `sint32` and so forth). I found it a bit cumbersome to dig up and use explicit ranges for

https://github.com/HypothesisWorks/hypothesis/blob/8a76f8afe38411b95399cef315b6593ee8db6c11/hypothesis-python/src/hypothesis/strategies/_internal/numbers.py#L133-L138

and so I was wondering if you guys would be open to a PR that expands the `integers()` strategy like so:
```python
def integers( 
    min_value: Optional[int] = None,
    max_value: Optional[int] = None,
    ctype: Optional[Literal["uint8", "sint8", ... ]] = None,  # 8b, 16b, 32b, 64b, maybe even 128b integers, signed and unsigned.
 ) -> SearchStrategy[int]:
    """ ... """
    if ctype is not None:
        if min_value or max_value:
            raise InvalidArgument("Unable to use min_value or max_value if the ctype argument is used.")
        if ctype == "uint8":
            min_value = 0
            max_value = 255
        elif ctype == "sint8":
            min_value = -128
            max_value = 127
        # And so forth.
```
This is somewhat similar to [`floats()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.floats)’s `width` argument.

**Comment by Zac-HD** [comment]
I've so far avoided this for two reasons:

1. (major) `min_value` and `max_value` allow you to express exactly the same constraints.  This isn't true for floats, where the width affects resolution as well as the representable range.
2. (minor) there are multiple conventions we could use: [struct format codes](https://docs.python.org/3/library/struct.html#format-characters)[^1], int/uint, sint/uint, one of the [many sets of names for integer types](https://en.wikipedia.org/wiki/Integer_(computer_science)), etc.  Specifically for `[u]int{8,16,32,64,128}`, we already have similar logic in `from_dtype()` for array users.

I think that the first objection is fatal for this proposal, but maybe sharing a recipe instead of changing the API would be sufficient?

[^1]: I've considered adding a `from_struct(format: str, /, *, pack: bool)` strategy in the past, but it's easy enough to write downstream.  Good for a recipes section of the docs, though...
