### ISSUE TITLE
Allow exact values in `st.builds()` arguments

### ISSUE THREAD

**Issue by ketozhang** [HypothesisWorks/hypothesis#3775]
Are there any strong opposition to allowing non-strategy objects in `st.builds()` positional and keyword arguments to be handled as exact values (i.e., as if it was passed in with `st.just()`?

**Current Behavior**
```python
@given(st.builds(MyClass, x=st.integers(), y=st.just("foobar")))
def test():
  ...
```

**Desired Behavior**
```python
@given(st.builds(MyClass, x==st.integers(), y="foobar"))
def test():
  ...

# Currently causes:
#       InvalidArgument: Expected a SearchStrategy but got mapping['y']='foobar' (type=str)
```

**Comment by Zac-HD** [comment]
Yes - it complicates the interface, which is a cost that grows surprisingly quickly and is disproportionately bad for complicated use-cases.

The current workarounds with just() or functools.partial() also seem fine to me, and I think that since these are necessary tools for complex use-cases there's some value in making them the idiomatic solution in simple cases too.

**Comment by ketozhang** [comment]
Well it's a UX consideration—I can never use hypothesis without constantly going referring back to [What you can generate and how](https://hypothesis.readthedocs.io/en/latest/data.html#what-you-can-generate-and-how). Even so what keyword do I search for to figure out it's `st.just()`.
