### ISSUE TITLE
Executing exactly n tests, and no more.

### ISSUE THREAD

**Issue by Wyko** [HypothesisWorks/hypothesis#3939]
Is there any way to have Hypothesis run no more than a specified number of tests? I know there's the `max_examples` option, but I've noticed that it can still allow multiple tests to run even if you set it to `1`. Sometimes I want to run a test exactly once to know if something works.

**Comment by Zac-HD** [comment]
No, because Hypothesis might have to give up on a test part-way through - e.g. because of an `assume(False)`, or a `data.draw(...)` which was unsatisfiable - and so we don't count invalid/partial-attempts towards the max examples.

If none of those apply, you can disable shrinking with the `phases=` setting and set `report_multiple_bugs=False`, and should then see only that many tests.  Of course, it's also possible that the first and simplest test case just misses a bug!
