### ISSUE TITLE
Allow `max_value` and `min_value` to control range for all numpy dtypes

### ISSUE THREAD

**Issue by dcherian** [HypothesisWorks/hypothesis#3951]
It looks like these are only obeyed for floating dtypes (https://hypothesis.readthedocs.io/en/latest/_modules/hypothesis/extra/numpy.html#from_dtype).

It would be quite useful to limit for the other dtypes too.

**Comment by Zac-HD** [comment]
I think we already do support it for signed and unsigned integers ([via this helper](https://github.com/HypothesisWorks/hypothesis/blob/5578efc734aeeaf3375b69e2d8fc77de9d80cc9a/hypothesis-python/src/hypothesis/extra/numpy.py#L151-L162)); complex numbers don't have a natural ordering but we do support min/max magnitude (as for `st.complex_numbers()`), and while it'd be nice to support bounds on datetimes and timedeltas it's really not clear how to do so effectively given that the temporal resolution can vary.

**Comment by dcherian** [comment]
Thanks.I was looking to control the range here: https://github.com/HypothesisWorks/hypothesis/blob/5578efc734aeeaf3375b69e2d8fc77de9d80cc9a/hypothesis-python/src/hypothesis/extra/numpy.py#L222-L225

But you're right `max_value` is not a good name for control the ints thatget cast to datetime.

**Comment by Zac-HD** [comment]
Indeed - if we have bounds here, they should be expressed over the represented moments or durations, not the underlying integer.  But in that case, there's no one value which has both the precision to bound (sub) nanosecond granularity, and the magnitude to bound year granularity!

Hypothesis tends to solve such problems by avoiding them, so that users can write their own strategy with whatever specific decisions make sense downstream.

**Comment by dcherian** [comment]
Sounds good.
