### ISSUE TITLE
Using `builds` arguments for reprs may produce worse results than pretty printing

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#4037]
Consider the following example:

```
from hypothesis import given, strategies as st


class Foo:
    def __init__(self, random):
        ...

    def __repr__(self):
        return "A perfectly good repr"


@given(st.builds(Foo, st.randoms(use_true_random=False)))
def test_foo(foo):
    assert False
```

This will print:

```
Falsifying example: test_foo(
     foo=Foo(HypothesisRandom(generated data)),
)
```

This is remarkably unhelpful compared to just returning Foo's perfectly good repr..

I'm actually not clear what the circumstances where we'd want the `builds` arguments to be the repr here are and I don't want to suggest complicated heuristics for fixing this until I understand the use case better, but this does seem like a case where it's clearly worse.

(In the example that prompted this I just switched over to using composite, so it's not too hard to work around, but it's a shame to lose the convenience of `builds` where it works)

**Comment by Zac-HD** [comment]
The real reason was to enable https://github.com/HypothesisWorks/hypothesis/pull/3624, which is queued up behind the other engine changes in https://github.com/HypothesisWorks/hypothesis/issues/3921.  I expected to have explain mode done early last year, but, well, stuff has a way of coming up.

A secondary reason is that it's often easier to copy-paste this into `@example()` / more likely to succeed at automatically dumping a patch.

It does seem likely that we can improve this with some heuristics for when to use the builtin repr anyway.

**Comment by DRMacIver** [comment]
> A secondary reason is that it's often easier to copy-paste this into @example() / more likely to succeed at automatically dumping a patch.

This makes sense, and might be a good guideline for the heuristic, because one reason why this is an example of the feature being bad is that you *can't* do that (you can't with the repr I provided here of course either, but in my prompting example the value was an attrs defined class that would have evaluated just fine)
