### ISSUE TITLE
patch with numpy arrays does not work out of the box

### ISSUE THREAD

**Issue by JohannesBuchner** [HypothesisWorks/hypothesis#4116]
Hypothesis suggests a patch with:
`git apply .hypothesis/patches/2024-09-26--302c8f80.patch` to add failing examples to your code.

First of all, the instruction is wrong, -p0 is needed instead of the git apply default -p1, because the patch already contains the correct path (tests/test_example.py instead of ./tests/test_example.py).

But after that, the patch gives invalid code leading to the error: "NameError: name 'array' is not defined. Did you forget to import 'array'". 

For a concrete example, `@given` is original, `@example` was added by the patch:
```
@given(
    mu=arrays(np.float64, (6,), elements=st.floats(-10, 10)),
    x=arrays(np.float64, (6,), elements=st.floats(-10, 10)),
    A=arrays(np.float64, (6,6), elements=st.floats(-10, 10)).filter(
        lambda A: np.std(A)>1e-6 and not (A==0).all() and not (np.diag(A)==0).any())
)
@example(
    mu=array([0., 0., 0., 0., 0., 0.]),  # or any other generated value
    x=array([0., 0., 0., 0., 0., 0.]),
    A=array([[1., 0., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1., 1.]]),
).via('discovered failure')
def test_stuff(mu, x, A):
```

The fix is quite trivial: `import numpy as np` means `array` should be replaced by `np.array`.

When generating the patch, could this case of numpy arrays please be handled for convenience, namely the three common cases "import numpy", "import numpy as np" and "from numpy import array"?

Python 3.12.3
pytest-8.2.1
hypothesis-6.112.1

**Comment by Zac-HD** [comment]
Instead of suggesting `-p0`, I'm inclined to just make the paths work either way by using `f"./{fname}"` here:

https://github.com/HypothesisWorks/hypothesis/blob/879225d8836c657fe970ceb1a95df072e06352d4/hypothesis-python/src/hypothesis/extra/_patching.py#L208-L209

------------

Dealing with `NameError` can be trickier - I don't want to special-case numpy.  We do have some useful tricks in [the Ghostwriter](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/ghostwriter.py) - albeit coming from the opposite direction - so I'm confident that with some inspection of the generated code and of the global namespace we can avoid many if not all of these errors.

**Comment by JohannesBuchner** [comment]
Thank you @Zac-HD
