### ISSUE TITLE
Hypothesis unable to generate "large" dictionnaries

### ISSUE THREAD

**Issue by ClementWalter** [HypothesisWorks/hypothesis#4197]
This is the MWE I'm having trouble with

```
    @given(
        obj=st.dictionaries(st.binary(), st.binary(), min_size=1_000, max_size=100_000)
    )
    @settings(suppress_health_check=[HealthCheck.data_too_large, HealthCheck.too_slow])
    def test_hypothesis(self, obj: Mapping[Bytes, Bytes]):
        print(obj)
```

this won't just run, raising "Unsatisfiable: Unable to satisfy assumptions of test_hypothesis"

Added the `suppress_health_check` as suggested by the first error message. Is there a limit to the size? if so, why am I able to set `max_size=100_000` ?

**Comment by tybug** [comment]
You're correct this is due to size limits. Hypothesis places a limit on the "size" of generate inputs, but this is measured in terms of "quantity of randomness consumed", so it's hard to place an explicit cap of e.g. no more than n inputs in a dictionary. Though we do have precedent in https://github.com/HypothesisWorks/hypothesis/issues/3892, using the invariant of "each choice consumes ≥1 byte"—and indeed you'll run into this error with `min_size=10_000`.

There are several interactions here:
- the initial "data too large" health check (which was silenced)
- if the smallest input is very large, this is a separate [`large_base_example`](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.HealthCheck.large_base_example) health check. However, the zero-buffer example here is invalid due to retrying unique dictionary keys, so this does not fire.
- every other input is an overrun (too large to finish generating)

I think the health checks are doing the best job they can here. The error message assumes that `runner.valid_examples == 0` is being hit due to difficult or impossible `assume` statements in the test function, which is misleading in this case due to overruns. Probably we should append a `" due to generating {runner.overrun_examples} (of {runner.total_examples}) which were too large"` to the error message in the case that over half the non-valid inputs are overruns, or alternatively note that the unsatisfiable could be due to (1) filters or (2) too large inputs if either invalid or overrun examples are significant in number respectively?

**Comment by ClementWalter** [comment]
is there a way to increase this limit on the quantity of randomness consumed?

**Comment by ClementWalter** [comment]
(btw you can remove this comment after reading but this lib is so so dope, thanks you so much!)

**Comment by tybug** [comment]
We don't expose a way to control the maximum size, no. You can in principle monkey-patch `BUFFER_SIZE`, but this is an abuse of internals which we don't recommend or formally support 🙂

**Comment by tybug** [comment]
We've improved this error message in #4199!
