### ISSUE TITLE
Enhancement - precision flag for strategies.floats

### ISSUE THREAD

**Issue by YeChen-IDM** [HypothesisWorks/hypothesis#466]
In some of my test cases, I want to test some floating point numbers with less significant digits. It will be very useful if you can have a precision flag for strategies.floats.

**Comment by alexwlchan** [comment]
It’s possible to construct an okay strategy for low precision floats with the existing `floats()` strategy and `map()`, like so:

```python
from hypothesis.strategies import floats

def limited_precision_floats(precision, *args, **kwargs):
    return floats(*args, **kwargs).map(lambda x: round(x, precision))

for _ in range(10):
    print(limited_precision_floats(precision=2).example())
```

This isn’t perfect – in particular, the imprecision of floating point numbers means you sometimes get extra digits anyway:

```console
$ python floats.py
-6.01118091373e+18
0.7
3.402823466e+38
0.0
-0.81
0.05
5.58461584997e+18
-inf
0.0
-5.64934847752e+17
```

I will freely admit that floating point arithmetic is quite complicated and I don’t understand all its nuances, so there are probably more bugs in this – but this might get you started.

**Comment by alexwlchan** [comment]
Related: #420.

**Comment by DRMacIver** [comment]
I agree limiting precision for floating points would be useful, but significant digits isn't really a concept that maps well to floating point. If we do add a precision flag it would probably be best for it to be in terms of powers of 2 (which floating point is exact with respect to), rather than powers of 10.

**Comment by Zac-HD** [comment]
Floating-point numbers don't have any concept of significant figures, as they consist of sign bit + exponent bits + mantissa bits.  Note that floats are not always equal to `mantissa * 2 ^ exponent` - there are special bit patterns for infinities and not-a-number.  However messing with bit-patterns is well beyond the scope of a general-purpose floating point strategy - if you really need to do this you should draw eight bytes, modify them as desired, and use the `struct` module to convert them to a float.

**Comment by DRMacIver** [comment]
I think we should leave the issue open. It's a difficult feature, but I don't think it's an unreasonable thing to want (as long as it's powers of two rather than ten). A lot of the Hypothesis strategies have a large number of configurable knobs and dials, so just because floats is a general purpose strategy doesn't mean it couldn't be restricted in this particular way.

I've looked into implementing this and as you point out the representation of floating point numbers makes it, um, not much fun, so I don't think any of us are going to get to it soon unless it falls out of other work or is funded, but if anything that makes it a good candidate for inclusion so people don't have to repeat the experience once it's done.

**Comment by Zac-HD** [comment]
Well, alright.  Maybe we should have an issue label `low-priority` to make the status of this and a few other things clear?

**Comment by DRMacIver** [comment]
To be honest, low priority is probably the default. Things only become high priority if someone is motivated enough to work on it out of their own interest or to fund someone else to do so. This is particularly true now that Hypothesis is relatively stable - there's plenty of stuff that can be improved on it, but there aren't really any pressing lacks unless something becomes broken due to things moving under us.

**Comment by Zac-HD** [comment]
I'd really like to close this issue.

"significant digits" is simply not a concept that applies to IEEE 754 floats - the closest I can work out is a mask for the low bits of the mantissa.  (which is how we prefer to shrink floats since #816)

Very few users of Hypothesis understand floats deeply enough for this kind of bit-manipulation to be useful, and I'm concerned that by adding a precision argument we would mislead them.  

If anyone has a specific example of a test that needs such an argument to the `floats()` strategy - ie will fail otherwise - and where this does not indicate a float-related problem in the system under test, please open a new issue and I'll be very interested in exploring it.  However this issue is too vague to solve and IMO should remain closed.
