### ISSUE TITLE
Deprecation warning does not blame user code correctly

### ISSUE THREAD

**Issue by mithrandi** [HypothesisWorks/hypothesis#652]
From IRC:
```
<idnar> …/hypothesis/searchstrategy/deferred.py:81: HypothesisDeprecationWarning: Use hypothesis.strategies.datetimes, which supports full-precision bounds and has a simpler API.
<idnar> that message doesn't actually tell me _what_ is deprecated
<tos9> idnar: It's hypothesis.extras.datetime.datetimes that's deprecated
<tos9> But I think all the warnings are possibly missing a stacklevel
<tos9> because they don't point at the calling code
```

**Comment by Zac-HD** [comment]
from hypothesis.extra.datetime import datetimes
    datetimes().example()

gives a warning pointing into Hypothesis internals.

However, I think this is due to lazy evaluation rather than a stack error as such; and the proper fix is probably to address the deeper issue of misattributed exceptions in deferred strategy creation.

**Comment by Zac-HD** [comment]
Nope, turns out it's a lot simpler than that - purely a presentation issue where we should pass `stacklevel=2` but currently have `stacklevel=3`; the traceback is fine but we've told the warnings machinery not to display the relevant frame!  Fix incoming :smile:
