### ISSUE TITLE
Add a `full_match` argument to `st.from_regex()`

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis#840]
Just reading #839, and thinking of what I skimmed on the hypothesis-regex PRs, I wonder if the need for boundary markers is strongly signalled enough? And if not, how we might make it clearer.

One way to make it more visible would be to add a `full_match` parameter to the strategy, which automatically adds boundary markers if not already present. That feels like it wouldn’t be a huge amount of work, and might make this limitation clearer. But I missed most of the initial discussion on this strategy, so I might be missing something.

What do other people/maintainers think?

(I’m assuming prepending a dollar to a string without throwing a TypeError is possible, because strings are obviously so easy and error-free to work with…)

**Comment by DRMacIver** [comment]
I feel like it's reasonably strongly signalled! The following is the concluding paragraph of the docstring:

> If you want the generated string to match the whole regex you should use boundary markers. So e.g. r"\A.\Z" will return a single character string, while "." will return any string, and r"\A.$" will return a single character optionally followed by a "\n".

It would probably be reasonable to add a `full_match` parameter. We went with the "a string containing a match" semantics because full matching plays very badly with things like lookahead, but adding it in as an option by just literally inserting boundary markers (which are "\A" and  "\Z", not "." and "$") and failing to produce any results in that scenario is perfectly reasonable.

**Comment by Zac-HD** [comment]
I agree with David - the current behaviour is a good default but adding an argument (that adds `\A` and `\Z` boundaries) is also pretty useful.  I'd prefer that the new parameter be a verb or verb phrase, but don't have any good suggestions.  (`match_all`?)

Considerations:  we rejected a `flags` argument last time on the basis that `regex` can be compiled with flags, but if we're adding arguments that would be the natural second argument and we can only do that once.  On the other hand, how would we handle conflicting flags if both were given?  I still like our current system and propose no change, but thought it worth mentioning.

**Comment by nbgl** [comment]
Claimed by yours truly at PyCon sprints (see #1513).
