### ISSUE TITLE
Strategies for matrices (numpy arrays) from the classical compact groups

### ISSUE THREAD

**Issue by jbweston** [HypothesisWorks/hypothesis#855]
For scientific (especially physics) applications often one wants to draw matrices that satisfy certain properties (e.g. unitarity, orthogonality etc.). This does not seem to be possible within the current `extras.numpy` module because (AFAICT) it only allows us to specify a strategy for *individual* elements, and does not allow to specify ~~overall properties of the generated matrices~~ statistical correlations *between* elements.

Is this something that would be useful to include in Hypothesis?

**Comment by jbweston** [comment]
I should probably add that I would be willing to have a crack at implementing this.

For certain classes of matrices it would be relatively simple to implement strategies as "wrappers" (e.g. to draw a Hermitian matrix one only needs to draw a random matrix `A` and return `0.5 * (A + A^\dag)`, but for orthogonal and unitary matrices the implementation would be a little more involved.

A good reference is [How to generate random matrices from the classical
compact groups](https://arxiv.org/abs/math-ph/0609050).

**Comment by jbweston** [comment]
It seems `scipy` already has at least some of these (see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ortho_group.html#scipy.stats.ortho_group) and [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.special_ortho_group.html#scipy.stats.special_ortho_group)).

**Comment by DRMacIver** [comment]
In general Hypothesis makes a point of not guaranteeing any statistical properties about the values it generates - Hypothesis is about generating single examples that trigger interesting behaviours in your program, not about trying to generate any particular distribution.

That said, the specific use-case of generating matrices with *non*-stastistical constraints between their elements (hermitian, orthogonal, unitary, etc) seems perfectly sensible and I'd be totally happy to include additional strategies for that.

Getting this to play nicely with the shrinker might be a little involved. If you'd like to have a crack at implementing this I'd definitely encourage you to do so, but I'd recommend opening a WIP pull request fairly early on in the process - you'll probably have to deal with a lot of the (currently under-documented) lower-level internals to get good behaviour. I'm/we're more than happy to answer any questions you have about that though.

**Comment by DRMacIver** [comment]
> In general Hypothesis makes a point of not guaranteeing any statistical properties about the values it generates - Hypothesis is about generating single examples that trigger interesting behaviours in your program, not about trying to generate any particular distribution.

I should elaborate on this: It's totally OK and generally beneficial from a *design* point of view to try and get a particular statistical distribution, it's just that what the actual distribution is is not part of the public API.

Often a good way to design Hypothesis strategies is to treat the underlying byte stream as a normal uniform random number generator and get a particular desirable distribution given that, so basically following the scipy implementation and reimplementing it on top of the primitives in https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/internal/conjecture/utils.py is probably a good place to start. It's just that the actual distribution seen in practice will then be more complicated than that.

**Comment by jbweston** [comment]
> Hypothesis is about generating single examples that trigger interesting behaviours in your program

>  the actual distribution is is not part of the public API.

Ah ok, I am completely new to Hypothesis, so I had not appreciated this. I was under the impression that a "strategy" was an abstraction around a particular space of values and a probability distribution (that you can tune based on your prior knowledge of where "interesting" regions of parameter space might be).

In any case I guess the important part is indeed being able to generate matrices with constraints, rather than the minutiae of how these are sampled.

I'll take another look at this in a week or so when I have a bit of free time.

**Comment by DRMacIver** [comment]
> Ah ok, I am completely new to Hypothesis, so I had not appreciated this. I was under the impression that a "strategy" was an abstraction around a particular space of values and a probability distribution (that you can tune based on your prior knowledge of where "interesting" regions of parameter space might be).

This is mostly true at the implementation level, but from a usage perspective the idea is more that the strategy just describes what's possible, and Hypothesis tries to single out one or more examples from that range of possibility that exhibit problems. So in a sense all the tests that pass are just an implementation detail that isn't exposed at the user facing level.

The main reason for this is that it gives us plenty of scope to change the implementation if we find distributions or techniques that are better at triggering interesting behaviour generically. Promising too much about the distribution ties our hands and reduces our ability to do that.

An example of where this might be relevant here: For numpy, Hypothesis tries to generate arrays as sparse arrays to reduce the amount of data it has to draw to generate an array. You might find a similar trick useful when generating an orthogonal array - e.g. you when generating an n by n  orthogonal array, you could pick some m <= n, generate that uniformly, then scale it up to an n by n array by mapping the smaller array to m indices of the n and filling in the remaining indices as 0 off the diagonal and one on the diagonal.

I'm not sure if that's a good idea. It's probably at least worth a try. But an advantage of not being specific about the distribution is we don't really have to try it up front - you could just start with doing the uniform distribution up front and if this turns out to be too slow for large matrices, implement this approach later.

**Comment by Zac-HD** [comment]
While I would still love to see this - and I'd be happy to help anyone who wants to write it - [our contributing guidelines now recommend developing new extras as independent packages](https://github.com/HypothesisWorks/hypothesis/blob/master/CONTRIBUTING.rst#pull-request-or-external-package).  Once complete and with some feedback from users, it can be merged just like `from_regex` was.
